import { createGameMainWorldRuntime } from './game-main-world-runtime.js';
import { createGameWorldDataRuntime } from '../designer/game-world-data-runtime.js';

type ValuePack = Record<string, any>;

export function createGameMainWorldBootstrap(options: ValuePack) {
    const worldRuntime = createGameMainWorldRuntime({
        fetchFreshJson: options.fetchFreshJson,
        assignEntityId: options.assignEntityId,
        createButton: options.createButton,
        createDoor: options.createDoor,
        createCreature: options.createCreature,
        createCollectable: options.createCollectable,
        getEntityLists: options.getEntityLists,
        setButtons: options.setButtons,
        setDoors: options.setDoors,
        setCreatures: options.setCreatures,
        setCollectables: options.setCollectables,
        getCollectedCollectableEntityIds: options.getCollectedCollectableEntityIds,
        setCollectedCollectableEntityIds: options.setCollectedCollectableEntityIds,
        getStoredCollectables: options.getStoredCollectables,
        setStoredCollectables: options.setStoredCollectables,
        getHeldCollectable: options.getHeldCollectable,
        setHeldCollectable: options.setHeldCollectable,
        setInventoryCycleIndex: options.setInventoryCycleIndex,
        syncGrenadeFuseState: options.syncGrenadeFuseState,
        isCollectableCollectedRuntime: options.isCollectableCollectedRuntime,
        markCollectableCollectedRuntime: options.markCollectableCollectedRuntime,
        getCreatureProjectileCollectablesRuntime: options.getCreatureProjectileCollectablesRuntime,
        getRenderableCollectablesRuntime: options.getRenderableCollectablesRuntime,
        getDesignerRenderableCollectablesRuntime: options.getDesignerRenderableCollectablesRuntime,
        getSavableCollectablesRuntime: options.getSavableCollectablesRuntime,
        getWorldDesigner: options.getWorldDesigner,
        getWorldMapRotatedBoundingBoxes: options.getWorldMapRotatedBoundingBoxes,
        getWorldMapBoundingBoxes: options.getWorldMapBoundingBoxes,
        setBlockInstanceRotatedBoundingBoxes: options.setBlockInstanceRotatedBoundingBoxes,
        getBlockInstanceRotatedBoundingBoxes: options.getBlockInstanceRotatedBoundingBoxes,
        findSpriteRectByType: options.findSpriteRectByType,
        getAstronautStartPosition: options.getAstronautStartPosition,
        getMapWidth: options.getMapWidth,
        getMapHeight: options.getMapHeight,
        spriteScale: options.spriteScale,
        worldBoundsPadding: options.worldBoundsPadding,
        setMapBounds: options.setMapBounds,
        rebuildMapBlockRenderCache: options.rebuildMapBlockRenderCache,
        initStars: options.initStars,
        invalidateTeleporterPadCaches: options.invalidateTeleporterPadCaches,
        getCachedWindReset: options.getCachedWindReset,
        updateAstronautStartPosition: options.updateAstronautStartPosition
    });

    const worldDataRuntime = createGameWorldDataRuntime({
        assignEntityId: options.assignEntityId,
        getMapBlocks: options.getMapBlocks,
        getButtonEntities: options.getButtonEntities,
        setButtonEntities: options.setButtonEntities,
        getDoorEntities: options.getDoorEntities,
        setDoorEntities: options.setDoorEntities,
        getCreatureEntities: options.getCreatureEntities,
        setCreatureEntities: options.setCreatureEntities,
        getCollectableEntities: options.getCollectableEntities,
        setCollectableEntities: options.setCollectableEntities,
        getTeleporterEntities: options.getTeleporterEntities,
        setTeleporterEntities: options.setTeleporterEntities,
        getWindEmitters: options.getWindEmitters,
        setWindEmitters: options.setWindEmitters,
        getWindSettings: options.getWindSettings,
        setWindSettings: options.setWindSettings,
        getAstronautStartPosition: options.getAstronautStartPosition,
        updateAstronautStartPosition: options.updateAstronautStartPosition,
        normalizeTeleporter: options.normalizeTeleporter,
        buildTeleportersFromMapMetadata: options.buildTeleportersFromMapMetadata,
        normalizeWindEmitter: options.normalizeWindEmitter,
        normalizeWindSettings: options.normalizeWindSettings,
        reconcileTeleporterRuntimePositions: options.reconcileTeleporterRuntimePositions,
        clearCollectedCollectableEntityIds: options.clearCollectedCollectableEntityIds,
        createDoor: options.createDoor,
        createButton: options.createButton,
        createCreature: options.createCreature,
        createCollectable: options.createCollectable,
        materializeAllMapChunksForSave: options.materializeAllMapChunksForSave,
        setSaveSnapshotInProgress: options.setSaveSnapshotInProgress,
        afterWorldDataMutated: worldRuntime.afterWorldDataMutated
    });

    return {
        ...worldRuntime,
        ...worldDataRuntime
    };
}

export function createGameMainWorldBootstrapFromState(state: ValuePack) {
    return createGameMainWorldBootstrap({
        fetchFreshJson: state.fetchFreshJson,
        assignEntityId: state.assignEntityId,
        createButton: state.createButton,
        createDoor: state.createDoor,
        createCreature: state.createCreature,
        createCollectable: state.createCollectable,
        getEntityLists: state.getEntityLists,
        setButtons: state.setButtons,
        setDoors: state.setDoors,
        setCreatures: state.setCreatures,
        setCollectables: state.setCollectables,
        getCollectedCollectableEntityIds: state.getCollectedCollectableEntityIds,
        setCollectedCollectableEntityIds: state.setCollectedCollectableEntityIds,
        getStoredCollectables: state.getStoredCollectables,
        setStoredCollectables: state.setStoredCollectables,
        getHeldCollectable: state.getHeldCollectable,
        setHeldCollectable: state.setHeldCollectable,
        setInventoryCycleIndex: state.setInventoryCycleIndex,
        syncGrenadeFuseState: state.syncGrenadeFuseState,
        isCollectableCollectedRuntime: state.isCollectableCollectedRuntime,
        markCollectableCollectedRuntime: state.markCollectableCollectedRuntime,
        getCreatureProjectileCollectablesRuntime: state.getCreatureProjectileCollectablesRuntime,
        getRenderableCollectablesRuntime: state.getRenderableCollectablesRuntime,
        getDesignerRenderableCollectablesRuntime: state.getDesignerRenderableCollectablesRuntime,
        getSavableCollectablesRuntime: state.getSavableCollectablesRuntime,
        getWorldDesigner: state.getWorldDesigner,
        getWorldMapRotatedBoundingBoxes: state.getWorldMapRotatedBoundingBoxes,
        getWorldMapBoundingBoxes: state.getWorldMapBoundingBoxes,
        setBlockInstanceRotatedBoundingBoxes: state.setBlockInstanceRotatedBoundingBoxes,
        getBlockInstanceRotatedBoundingBoxes: state.getBlockInstanceRotatedBoundingBoxes,
        findSpriteRectByType: state.findSpriteRectByType,
        getAstronautStartPosition: state.getAstronautStartPosition,
        getMapWidth: state.getMapWidth,
        getMapHeight: state.getMapHeight,
        spriteScale: state.spriteScale,
        worldBoundsPadding: state.worldBoundsPadding,
        setMapBounds: state.setMapBounds,
        rebuildMapBlockRenderCache: state.rebuildMapBlockRenderCache,
        initStars: state.initStars,
        invalidateTeleporterPadCaches: state.invalidateTeleporterPadCaches,
        getCachedWindReset: state.getCachedWindReset,
        updateAstronautStartPosition: state.updateAstronautStartPosition,
        getMapBlocks: state.getMapBlocks,
        getButtonEntities: state.getButtonEntities,
        setButtonEntities: state.setButtonEntities,
        getDoorEntities: state.getDoorEntities,
        setDoorEntities: state.setDoorEntities,
        getCreatureEntities: state.getCreatureEntities,
        setCreatureEntities: state.setCreatureEntities,
        getCollectableEntities: state.getCollectableEntities,
        setCollectableEntities: state.setCollectableEntities,
        getTeleporterEntities: state.getTeleporterEntities,
        setTeleporterEntities: state.setTeleporterEntities,
        getWindEmitters: state.getWindEmitters,
        setWindEmitters: state.setWindEmitters,
        getWindSettings: state.getWindSettings,
        setWindSettings: state.setWindSettings,
        normalizeTeleporter: state.normalizeTeleporter,
        buildTeleportersFromMapMetadata: state.buildTeleportersFromMapMetadata,
        normalizeWindEmitter: state.normalizeWindEmitter,
        normalizeWindSettings: state.normalizeWindSettings,
        reconcileTeleporterRuntimePositions: state.reconcileTeleporterRuntimePositions,
        clearCollectedCollectableEntityIds: state.clearCollectedCollectableEntityIds,
        materializeAllMapChunksForSave: state.materializeAllMapChunksForSave,
        setSaveSnapshotInProgress: state.setSaveSnapshotInProgress
    });
}
