import { buildGameMainLoopStateAccessors } from './game-main-loop-runtime-builder.js';

type ValuePack = Record<string, any>;

export function createSharedRuntimeContextFromState(state: ValuePack) {
    return {
        astronaut: state.astronaut,
        movementSettings: state.movementSettings,
        creatureProjectileSettings: state.creatureProjectileSettings,
        spriteScale: state.spriteScale,
        canvas: state.canvas,
        keys: state.keys,
        getPrevKeys: state.getPrevKeys,
        getFacingLeft: state.getFacingLeft,
        getFacingSign: state.getFacingSign,
        getThrowAngleDegrees: state.getThrowAngleDegrees,
        setThrowAngleDegrees: state.setThrowAngleDegrees,
        getThrowGuideDots: state.getThrowGuideDots,
        setThrowGuideDots: state.setThrowGuideDots,
        getThrowGuideDotEmitTimer: state.getThrowGuideDotEmitTimer,
        setThrowGuideDotEmitTimer: state.setThrowGuideDotEmitTimer,
        getCreatureEntities: state.getCreatureEntities,
        getCollectableEntities: state.getCollectableEntities,
        getHeldCollectable: state.getHeldCollectable,
        setHeldCollectable: state.setHeldCollectable,
        getStoredCollectables: state.getStoredCollectables,
        getInventoryCycleIndex: state.getInventoryCycleIndex,
        setInventoryCycleIndex: state.setInventoryCycleIndex,
        getAstronautPosition: state.getAstronautPosition,
        getGameState: state.getGameState,
        getAstronaut: state.getAstronaut,
        getDoorCount: state.getDoorCount,
        getBulletImpactAudioSettings: state.getBulletImpactAudioSettings,
        getAstronautRect: state.getAstronautRect,
        getAstronautAimPoint: state.getAstronautAimPoint,
        getAstronautRenderedWorldSprite: state.getAstronautRenderedWorldSprite,
        getEntityCollisionBounds: state.getEntityCollisionBounds,
        getEntityCenter: state.getEntityCenter,
        getEntityRect: state.getEntityRect,
        getEntityFrontAnchorPoint: state.getEntityFrontAnchorPoint,
        getEntitySideAnchorPoint: state.getEntitySideAnchorPoint,
        getEntityPositionFromCenter: state.getEntityPositionFromCenter,
        getSpriteVisibleBounds: state.getSpriteVisibleBounds,
        isRenderedSpriteOpaqueAtWorld: state.isRenderedSpriteOpaqueAtWorld,
        doRenderedSpritesOverlap: state.doRenderedSpritesOverlap,
        getRenderedEntityWorldSprite: state.getRenderedEntityWorldSprite,
        getChunkActivityForEntityPosition: state.getChunkActivityForEntityPosition,
        shouldRunChunkBandUpdate: state.shouldRunChunkBandUpdate,
        creatureChunkCadence: state.creatureChunkCadence,
        getCreatureAuthoredType: state.getCreatureAuthoredType,
        isBirdCreature: state.isBirdCreature,
        getStableCreatureAimCenter: state.getStableCreatureAimCenter,
        isTurretLikeCreature: state.isTurretLikeCreature,
        hasCreatureLineOfSight: state.hasCreatureLineOfSight,
        getCreatureTargetPoint: state.getCreatureTargetPoint,
        birdTrackReleaseRangeMultiplier: state.birdTrackReleaseRangeMultiplier,
        birdTrackReleaseRangePadding: state.birdTrackReleaseRangePadding,
        birdAvoidanceVerticalThreshold: state.birdAvoidanceVerticalThreshold,
        clampToRange: state.clampToRange,
        moveCreatureWithEnvironmentCollisions: state.moveCreatureWithEnvironmentCollisions,
        getNextCreatureFireAt: state.getNextCreatureFireAt,
        getAnimatedBirdSpriteType: state.getAnimatedBirdSpriteType,
        getTurretFacingRotations: state.getTurretFacingRotations,
        spawnCreatureCarryProxy: state.spawnCreatureCarryProxy,
        gameAudio: state.gameAudio,
        heldCollectableHandInset: state.heldCollectableHandInset,
        heldCollectableHandOverlap: state.heldCollectableHandOverlap,
        markCollectableCollected: state.markCollectableCollected,
        isCollectableCollected: state.isCollectableCollected,
        isGrenadeCollectable: state.isGrenadeCollectable,
        setGrenadeCollectableArmedState: state.setGrenadeCollectableArmedState,
        removeCollectableEntity: state.removeCollectableEntity,
        assignEntityId: state.assignEntityId,
        getSound: state.getSound,
        saveSound: state.saveSound,
        isCreatureProjectileCollectable: state.isCreatureProjectileCollectable,
        getCollectablePhysicsSettings: state.getCollectablePhysicsSettings,
        moveCollectableHorizontally: state.moveCollectableHorizontally,
        moveCollectableVertically: state.moveCollectableVertically,
        getMushroomBlocks: state.getMushroomBlocks,
        projectileChunkCadence: state.projectileChunkCadence,
        collectableChunkCadence: state.collectableChunkCadence,
        mushroomAmbientRange: state.mushroomAmbientRange,
        mushroomAmbientBaseVolume: state.mushroomAmbientBaseVolume,
        mushroomAmbientMinDelayMs: state.mushroomAmbientMinDelayMs,
        mushroomAmbientMaxDelayMs: state.mushroomAmbientMaxDelayMs,
        syncGrenadeFuseState: state.syncGrenadeFuseState,
        getDynamicObjectHeadBounceLaunchSpeed: state.getDynamicObjectHeadBounceLaunchSpeed,
        getDynamicObjectPushScale: state.getDynamicObjectPushScale,
        getDynamicObjectPushedVelocity: state.getDynamicObjectPushedVelocity,
        applyDynamicObjectGravity: state.applyDynamicObjectGravity,
        collidesAtSide: state.collidesAtSide,
        getFloorSnapAmount: state.getFloorSnapAmount,
        applyDynamicObjectBounceRestitution: state.applyDynamicObjectBounceRestitution,
        applyDynamicObjectGroundFriction: state.applyDynamicObjectGroundFriction,
        getEffectiveWindToggles: state.getEffectiveWindToggles,
        getWindSettings: state.getWindSettings,
        getWindDebugToggles: state.getWindDebugToggles,
        getActiveWindEmittersNearAstronaut: state.getActiveWindEmittersNearAstronaut,
        computeEmitterWindAccelerationAtPoint: state.computeEmitterWindAccelerationAtPoint,
        applySurfaceWindField: state.applySurfaceWindField,
        normalizeWindSettings: state.normalizeWindSettings,
        getSurfaceWindEdgeProximity: state.getSurfaceWindEdgeProximity,
        getSurfaceWindBoundaryOvershoot: state.getSurfaceWindBoundaryOvershoot,
        getProjectileKindForFireMode: state.getProjectileKindForFireMode,
        getProjectileSettings: state.getProjectileSettings,
        updateProjectileFlightFrame: state.updateProjectileFlightFrame,
        getProjectileAngleDegrees: state.getProjectileAngleDegrees,
        getDefaultGrenadeExplosionPower: state.getDefaultGrenadeExplosionPower,
        getGrenadeExplosionRadius: state.getGrenadeExplosionRadius,
        getGrenadeExplosionPower: state.getGrenadeExplosionPower,
        getExplosionDamageSource: state.getExplosionDamageSource,
        getCreatureProjectilePhysicsSettings: state.getCreatureProjectilePhysicsSettings,
        spawnProjectileImpactEffect: state.spawnProjectileImpactEffect,
        applyAstronautProjectileImpact: state.applyAstronautProjectileImpact,
        applyAstronautDamage: state.applyAstronautDamage,
        applyAstronautImpact: state.applyAstronautImpact,
        isCoroniumExplosionAtCenter: state.isCoroniumExplosionAtCenter,
        applyExplosionDamageToDestructibles: state.applyExplosionDamageToDestructibles,
        convertProjectileToEnergyPodCollectable: state.convertProjectileToEnergyPodCollectable,
        triggerAstronautEmergencyTeleport: state.triggerAstronautEmergencyTeleport,
        spawnGrenadeExplosionEffect: state.spawnGrenadeExplosionEffect,
        getSolidBlockAtWorld: state.getSolidBlockAtWorld,
        getSpriteMap: state.getSpriteMap,
        getMapBlocks: state.getMapBlocks,
        getDoorEntities: state.getDoorEntities,
        getButtonEntities: state.getButtonEntities,
        getTeleporterEntities: state.getTeleporterEntities
    };
}

export function createExtraRuntimeContextFromState(state: ValuePack) {
    return {
        CHUNK_SYNC_INTERVAL_FRAMES: state.CHUNK_SYNC_INTERVAL_FRAMES,
        MAP_HEIGHT: state.MAP_HEIGHT,
        MAP_WIDTH: state.MAP_WIDTH,
        MOVEMENT_SETTINGS: state.MOVEMENT_SETTINGS,
        SPRITE_COL_FLY_DIAGONAL: state.SPRITE_COL_FLY_DIAGONAL,
        SPRITE_COL_FLY_DOWN: state.SPRITE_COL_FLY_DOWN,
        SPRITE_COL_FLY_FLOAT: state.SPRITE_COL_FLY_FLOAT,
        SPRITE_COL_FLY_RIGHT: state.SPRITE_COL_FLY_RIGHT,
        SPRITE_COL_STAND: state.SPRITE_COL_STAND,
        SPRITE_COL_WALK_END: state.SPRITE_COL_WALK_END,
        SPRITE_COL_WALK_RIGHT1: state.SPRITE_COL_WALK_RIGHT1,
        SPRITE_COL_WALK_RIGHT2: state.SPRITE_COL_WALK_RIGHT2,
        SPRITE_COL_WALK_START: state.SPRITE_COL_WALK_START,
        SPRITE_ROW: state.SPRITE_ROW,
        SPRITE_SCALE: state.SPRITE_SCALE,
        STARFIELD_HEIGHT: state.STARFIELD_HEIGHT,
        TELEPORT_ANIM_FRAMES: state.TELEPORT_ANIM_FRAMES,
        applyButtonTeleporterLinks: state.applyButtonTeleporterLinks,
        applyGravity: state.applyGravity,
        applyLandingMomentum: state.applyLandingMomentum,
        applySurfaceWindCarryToAstronaut: state.applySurfaceWindCarryToAstronaut,
        astronautRenderer: state.astronautRenderer,
        getAstronautSpriteSource: state.getAstronautSpriteSource,
        bulletImpactParticles: state.bulletImpactParticles,
        projectileImpactEffects: state.projectileImpactEffects,
        windParticles: state.windParticles,
        buttonEntities: state.buttonEntities,
        collectableEntities: state.collectableEntities,
        creatureEntities: state.creatureEntities,
        doorEntities: state.doorEntities,
        buttonOnSound: state.buttonOnSound,
        buttonPressTimestamps: state.buttonPressTimestamps,
        canAstronautFitCollisionProfile: state.canAstronautFitCollisionProfile,
        checkAstronautCollisions: state.checkAstronautCollisions,
        chunkActivityManager: state.chunkActivityManager,
        computeAstronautWindAcceleration: state.computeAstronautWindAcceleration,
        computeLandingImpactDamage: state.computeLandingImpactDamage,
        ctx: state.ctx,
        gameState: state.gameState,
        doorCloseSound: state.doorCloseSound,
        doorDestructionEffects: state.doorDestructionEffects,
        doorOpenSound: state.doorOpenSound,
        drawCreatureOverlays: state.drawCreatureOverlays,
        drawDoorDestructionEffects: state.drawDoorDestructionEffects,
        drawEntities: state.drawEntities,
        drawMap: state.drawMap,
        drawTeleporterPads: state.drawTeleporterPads,
        drawWorldBoundingBoxOverlay: state.drawWorldBoundingBoxOverlay,
        emitJetpackDots: state.emitJetpackDots,
        filterTeleporterPadsFromBlocks: state.filterTeleporterPadsFromBlocks,
        getAnyBlockAtWorld: state.getAnyBlockAtWorld,
        getAstronautCollisionOffsets: state.getAstronautCollisionOffsets,
        getAstronautControlModifiers: state.getAstronautControlModifiers,
        getAstronautFacingDirectionForFlyPose: state.getAstronautFacingDirectionForFlyPose,
        getBlackBackgroundBlocks: state.getBlackBackgroundBlocks,
        getCameraOffset: state.getCameraOffset,
        getChunkActivityForWorldPosition: state.getChunkActivityForWorldPosition,
        getCreatureProjectileCollectables: state.getCreatureProjectileCollectables,
        getCurrentAstronautCollisionProfile: state.getCurrentAstronautCollisionProfile,
        getDesignerRenderableCollectables: state.getDesignerRenderableCollectables,
        getDirectDownTransitionSequence: state.getDirectDownTransitionSequence,
        getEffectiveViewportState: state.getEffectiveViewportState,
        getHeldMovementModifiers: state.getHeldMovementModifiers,
        getHorizontalTravelDirection: state.getHorizontalTravelDirection,
        getMapBlocksBehindAstronaut: state.getMapBlocksBehindAstronaut,
        getMapBlocksMaskAstronaut: state.getMapBlocksMaskAstronaut,
        getRenderableCollectables: state.getRenderableCollectables,
        getRenderableMapBlocks: state.getRenderableMapBlocks,
        getSpriteSheet: state.getSpriteSheet,
        getSpriteRectFromMap: state.getSpriteRectFromMap,
        getTeleporterPadKeySet: state.getTeleporterPadKeySet,
        handleAstronautMovement: state.handleAstronautMovement,
        hideBlackBackgroundBlocks: state.hideBlackBackgroundBlocks,
        getMapLoaded: state.getMapLoaded,
        mapLoaded: typeof state.getMapLoaded === 'function' ? state.getMapLoaded() : state.mapLoaded,
        mouseScreen: state.mouseScreen,
        mouseWorld: state.mouseWorld,
        performanceTracker: state.performanceTracker,
        popLatestTeleportLocation: state.popLatestTeleportLocation,
        rememberLastFlyPose: state.rememberLastFlyPose,
        rememberSound: state.rememberSound,
        resetFlyDownAnimationState: state.resetFlyDownAnimationState,
        resetFlySwitchAnimationState: state.resetFlySwitchAnimationState,
        resolveAstronautCreatureCollisions: state.resolveAstronautCreatureCollisions,
        scheduleNextFrame: state.scheduleNextFrame,
        setAstronautCollisionProfile: state.setAstronautCollisionProfile,
        showBlackBackgroundBlocks: state.showBlackBackgroundBlocks,
        spawnWindParticlesNearAstronaut: state.spawnWindParticlesNearAstronaut,
        startTeleportToLocation: state.startTeleportToLocation,
        syncButtonStatesToDoors: state.syncButtonStatesToDoors,
        syncMapChunksForViewport: state.syncMapChunksForViewport,
        updateAndDrawBulletImpactParticles: state.updateAndDrawBulletImpactParticles,
        updateAndDrawJetpackDots: state.updateAndDrawJetpackDots,
        updateAndDrawStars: state.updateAndDrawStars,
        updateAndDrawWindParticles: state.updateAndDrawWindParticles,
        updateAstronautEnergyRecovery: state.updateAstronautEnergyRecovery,
        updateCreatureSounds: state.updateCreatureSounds,
        updateDoorDestructionEffects: state.updateDoorDestructionEffects,
        updateProjectileImpactEffects: state.updateProjectileImpactEffects,
        updateTeleporterPadTeleporting: state.updateTeleporterPadTeleporting,
        getWalkSpeed: state.getWalkSpeed,
        walkSpeed: typeof state.getWalkSpeed === 'function' ? state.getWalkSpeed() : state.walkSpeed,
        isDesignerOpen: state.isDesignerOpen,
        windDebugToggles: state.windDebugToggles,
        windSettings: state.windSettings,
        getDownPressed: state.getDownPressed,
        getFacingLeft: state.getFacingLeft,
        getLeftPressed: state.getLeftPressed,
        downPressed: typeof state.getDownPressed === 'function' ? state.getDownPressed() : state.downPressed,
        facingLeft: typeof state.getFacingLeft === 'function' ? state.getFacingLeft() : state.facingLeft,
        leftPressed: typeof state.getLeftPressed === 'function' ? state.getLeftPressed() : state.leftPressed,
        remappedSpriteSheets: state.remappedSpriteSheets,
        getRightPressed: state.getRightPressed,
        rightPressed: typeof state.getRightPressed === 'function' ? state.getRightPressed() : state.rightPressed,
        saveSnapshotInProgress: state.saveSnapshotInProgress,
        showCreatureOverlays: state.showCreatureOverlays,
        showTightBoundingBoxes: state.showTightBoundingBoxes,
        showWorldBoundingBoxes: state.showWorldBoundingBoxes,
        getUpPressed: state.getUpPressed,
        upPressed: typeof state.getUpPressed === 'function' ? state.getUpPressed() : state.upPressed,
        astronautBoundingBoxes: state.astronautBoundingBoxes,
        blockInstanceRotatedBoundingBoxes: state.blockInstanceRotatedBoundingBoxes,
        worldMapBoundingBoxes: state.worldMapBoundingBoxes,
        worldMapRotatedBoundingBoxes: state.worldMapRotatedBoundingBoxes,
        drawCustomPalettePreview: state.drawCustomPalettePreview,
        drawSpritePreview: state.drawSpritePreview,
        drawSpriteSample: state.drawSpriteSample,
        ensureMapChunksAroundWorldPosition: state.ensureMapChunksAroundWorldPosition,
        ensureWorldBounds: state.ensureWorldBounds,
        afterWorldDataMutated: state.afterWorldDataMutated,
        clampCamera: state.clampCamera,
        getAstronautStartPosition: state.getAstronautStartPosition,
        getRawWorldData: state.getRawWorldData,
        getRawWorldDataForSave: state.getRawWorldDataForSave,
        getSpriteCatalog: state.getSpriteCatalog,
        getSpriteTypes: state.getSpriteTypes,
        syncRuntimeMapBounds: state.syncRuntimeMapBounds,
        updateAstronautStartPosition: state.updateAstronautStartPosition,
        loadAstronautStartPosition: state.loadAstronautStartPosition,
        loadButtons: state.loadButtons,
        loadCollectables: state.loadCollectables,
        loadCreatures: state.loadCreatures,
        loadDoors: state.loadDoors,
        loadMapBlocks: state.loadMapBlocks,
        loadPalettes: state.loadPalettes,
        loadSpriteMap: state.loadSpriteMap,
        loadTeleporters: state.loadTeleporters,
        loadWindData: state.loadWindData,
        createWorldDesigner: state.createWorldDesigner,
        deepClone: state.deepClone,
        getSoundEnabled: state.getSoundEnabled,
        setSoundEnabled: state.setSoundEnabled,
        setWindDebugToggle: state.setWindDebugToggle,
        makeBlackTransparent: state.makeBlackTransparent,
        normalizeBulletImpactAudioSettings: state.normalizeBulletImpactAudioSettings,
        normalizeSpriteSheetColors: state.normalizeSpriteSheetColors,
        previewSpriteSheetNormalization: state.previewSpriteSheetNormalization,
        replaceRawWorldData: state.replaceRawWorldData,
        calculateAstronautSpriteBoundingBoxes: state.calculateAstronautSpriteBoundingBoxes,
        calculateSpriteCollisionBoundingBoxes: state.calculateSpriteCollisionBoundingBoxes,
        initStars: state.initStars,
        rebuildBlockInstanceBoundingBoxes: state.rebuildBlockInstanceBoundingBoxes,
        rebuildRemappedSpriteSheets: state.rebuildRemappedSpriteSheets,
        resetAstronautToPosition: state.resetAstronautToPosition,
        requestImmediateFrame: state.requestImmediateFrame,
        getAstronautBoundingBoxes: state.getAstronautBoundingBoxes,
        setAstronautBoundingBoxes: state.setAstronautBoundingBoxes,
        getBlockInstanceRotatedBoundingBoxes: state.getBlockInstanceRotatedBoundingBoxes,
        setBulletImpactAudioSettings: state.setBulletImpactAudioSettings,
        getCachedWindEmittersFrameKey: state.getCachedWindEmittersFrameKey,
        setCachedWindEmittersFrameKey: state.setCachedWindEmittersFrameKey,
        getShowCreatureOverlays: state.getShowCreatureOverlays,
        setShowCreatureOverlays: state.setShowCreatureOverlays,
        getShowWorldBoundingBoxes: state.getShowWorldBoundingBoxes,
        setShowWorldBoundingBoxes: state.setShowWorldBoundingBoxes,
        getColorAliases: state.getColorAliases,
        getPalettes: state.getPalettes,
        getRawPaletteDefinitions: state.getRawPaletteDefinitions,
        getRemappedSpriteSheets: state.getRemappedSpriteSheets,
        getSpriteMap: state.getSpriteMap,
        setSpriteMap: state.setSpriteMap,
        setSpriteSheet: state.setSpriteSheet,
        getWorldDesigner: state.getWorldDesigner,
        setWorldDesigner: state.setWorldDesigner,
        getWorldMapBoundingBoxes: state.getWorldMapBoundingBoxes,
        setWorldMapBoundingBoxes: state.setWorldMapBoundingBoxes,
        getWorldMapRotatedBoundingBoxes: state.getWorldMapRotatedBoundingBoxes,
        setWorldMapRotatedBoundingBoxes: state.setWorldMapRotatedBoundingBoxes
    };
}

export function mergeRuntimeContexts(state: ValuePack) {
    Object.assign(state.sharedRuntimeContext, state.extraRuntimeContext, {
        creatureRuntime: state.creatureRuntime,
        creatureProjectileRuntime: state.creatureProjectileRuntime,
        getAimOriginPosition: state.getAimOriginPosition,
        updateHeldCollectablePosition: state.updateHeldCollectablePosition,
        isCollectableOverlappingAstronaut: state.isCollectableOverlappingAstronaut,
        handleCollectableInteractions: state.handleCollectableInteractions,
        releaseHeldCollectable: state.releaseHeldCollectable,
        updateThrowAngle: state.updateThrowAngle,
        updateAndDrawThrowGuide: state.updateAndDrawThrowGuide,
        resolveAstronautCollectableCollisions: state.resolveAstronautCollectableCollisions,
        updateSingleCollectablePhysics: state.updateSingleCollectablePhysics,
        updateCollectablePhysics: state.updateCollectablePhysics
    });
}

export function createLoopStateAccessorsFromState(state: ValuePack) {
    const rw = <T>(get: () => T, set: (value: T) => void) => ({ get, set });
    return buildGameMainLoopStateAccessors({
        activeAstronautCollisionProfile: rw(state.getActiveAstronautCollisionProfile, state.setActiveAstronautCollisionProfile),
        chunkSyncFrameCounter: rw(state.getChunkSyncFrameCounter, state.setChunkSyncFrameCounter),
        currentAstronautChunkActivity: rw(state.getCurrentAstronautChunkActivity, state.setCurrentAstronautChunkActivity),
        currentAstronautRenderState: rw(state.getCurrentAstronautRenderState, state.setCurrentAstronautRenderState),
        flyDir: rw(state.getFlyDir, state.setFlyDir),
        flyDownFacingLeft: rw(state.getFlyDownFacingLeft, state.setFlyDownFacingLeft),
        flyDownMode: rw(state.getFlyDownMode, state.setFlyDownMode),
        flyDownTransitionStep: rw(state.getFlyDownTransitionStep, state.setFlyDownTransitionStep),
        flyDownTransitionTimer: rw(state.getFlyDownTransitionTimer, state.setFlyDownTransitionTimer),
        flyDownTransitioning: rw(state.getFlyDownTransitioning, state.setFlyDownTransitioning),
        flyDownTravelDir: rw(state.getFlyDownTravelDir, state.setFlyDownTravelDir),
        flyHoldTimer: rw(state.getFlyHoldTimer, state.setFlyHoldTimer),
        flySwitchStep: rw(state.getFlySwitchStep, state.setFlySwitchStep),
        flySwitchTimer: rw(state.getFlySwitchTimer, state.setFlySwitchTimer),
        flySwitching: rw(state.getFlySwitching, state.setFlySwitching),
        isGameLoopRunning: rw(state.getIsGameLoopRunning, state.setIsGameLoopRunning),
        lastAstronautWindAcceleration: rw(state.getLastAstronautWindAcceleration, state.setLastAstronautWindAcceleration),
        lastFlyFlipSprite: rw(state.getLastFlyFlipSprite, state.setLastFlyFlipSprite),
        lastFlySpriteCol: rw(state.getLastFlySpriteCol, state.setLastFlySpriteCol),
        layDownVerticalFlipToggled: rw(state.getLayDownVerticalFlipToggled, state.setLayDownVerticalFlipToggled),
        prevKeys: rw(state.getPrevKeysState, state.setPrevKeysState),
        proneForcedByGeometry: rw(state.getProneForcedByGeometry, state.setProneForcedByGeometry),
        pronePoseActive: rw(state.getPronePoseActive, state.setPronePoseActive),
        simulationFrameCounter: rw(state.getSimulationFrameCounter, state.setSimulationFrameCounter),
        teleportAnimFrame: rw(state.getTeleportAnimFrame, state.setTeleportAnimFrame),
        teleportPhase: rw(state.getTeleportPhase, state.setTeleportPhase),
        teleportSlot: rw(state.getTeleportSlot, state.setTeleportSlot),
        teleportTarget: rw(state.getTeleportTarget, state.setTeleportTarget),
        teleporting: rw(state.getTeleporting, state.setTeleporting),
        walkAnimFrame: rw(state.getWalkAnimFrame, state.setWalkAnimFrame),
        walkAnimTimer: rw(state.getWalkAnimTimer, state.setWalkAnimTimer)
    });
}
