import { createGameMainWorldBootstrapFromState } from './game-main-world-bootstrap.js';

type ValuePack = Record<string, any>;

export function createGameMainWorldBootstrapFromContext(state: ValuePack) {
    return createGameMainWorldBootstrapFromState({
        fetchFreshJson: state.fetchFreshJson,
        assignEntityId: state.assignEntityId,
        createButton: state.createButton,
        createDoor: state.createDoor,
        createCreature: state.createCreature,
        createCollectable: state.createCollectable,
        getEntityLists: state.getEntityLists,
        setButtons: state.setButtons,
        setDoors: state.setDoors,
        setCreatures: state.setCreatures,
        setCollectables: state.setCollectables,
        getCollectedCollectableEntityIds: state.getCollectedCollectableEntityIds,
        setCollectedCollectableEntityIds: state.setCollectedCollectableEntityIds,
        getStoredCollectables: state.getStoredCollectables,
        setStoredCollectables: state.setStoredCollectables,
        getHeldCollectable: state.getHeldCollectable,
        setHeldCollectable: state.setHeldCollectable,
        setInventoryCycleIndex: state.setInventoryCycleIndex,
        syncGrenadeFuseState: state.syncGrenadeFuseState,
        isCollectableCollectedRuntime: state.isCollectableCollectedRuntime,
        markCollectableCollectedRuntime: state.markCollectableCollectedRuntime,
        getCreatureProjectileCollectablesRuntime: state.getCreatureProjectileCollectablesRuntime,
        getRenderableCollectablesRuntime: state.getRenderableCollectablesRuntime,
        getDesignerRenderableCollectablesRuntime: state.getDesignerRenderableCollectablesRuntime,
        getSavableCollectablesRuntime: state.getSavableCollectablesRuntime,
        getWorldDesigner: state.getWorldDesigner,
        getWorldMapRotatedBoundingBoxes: state.getWorldMapRotatedBoundingBoxes,
        getWorldMapBoundingBoxes: state.getWorldMapBoundingBoxes,
        setBlockInstanceRotatedBoundingBoxes: state.setBlockInstanceRotatedBoundingBoxes,
        getBlockInstanceRotatedBoundingBoxes: state.getBlockInstanceRotatedBoundingBoxes,
        findSpriteRectByType: state.findSpriteRectByType,
        getAstronautStartPosition: state.getAstronautStartPosition,
        getMapWidth: state.getMapWidth,
        getMapHeight: state.getMapHeight,
        spriteScale: state.spriteScale,
        worldBoundsPadding: state.worldBoundsPadding,
        setMapBounds: state.setMapBounds,
        rebuildMapBlockRenderCache: state.rebuildMapBlockRenderCache,
        initStars: state.initStars,
        invalidateTeleporterPadCaches: state.invalidateTeleporterPadCaches,
        getCachedWindReset: state.getCachedWindReset,
        getMapBlocks: state.getMapBlocks,
        getButtonEntities: state.getButtonEntities,
        setButtonEntities: state.setButtonEntities,
        getDoorEntities: state.getDoorEntities,
        setDoorEntities: state.setDoorEntities,
        getCreatureEntities: state.getCreatureEntities,
        setCreatureEntities: state.setCreatureEntities,
        getCollectableEntities: state.getCollectableEntities,
        setCollectableEntities: state.setCollectableEntities,
        getTeleporterEntities: state.getTeleporterEntities,
        setTeleporterEntities: state.setTeleporterEntities,
        getWindEmitters: state.getWindEmitters,
        setWindEmitters: state.setWindEmitters,
        getWindSettings: state.getWindSettings,
        setWindSettings: state.setWindSettings,
        normalizeTeleporter: state.normalizeTeleporter,
        buildTeleportersFromMapMetadata: state.buildTeleportersFromMapMetadata,
        normalizeWindEmitter: state.normalizeWindEmitter,
        normalizeWindSettings: state.normalizeWindSettings,
        reconcileTeleporterRuntimePositions: state.reconcileTeleporterRuntimePositions,
        clearCollectedCollectableEntityIds: state.clearCollectedCollectableEntityIds,
        materializeAllMapChunksForSave: state.materializeAllMapChunksForSave,
        setSaveSnapshotInProgress: state.setSaveSnapshotInProgress,
        updateAstronautStartPosition: state.updateAstronautStartPosition
    });
}
