import {
    createInspectorCoordinatorFromContext,
    createInteractionCoordinatorFromContext,
    createModalCoordinatorFromContext
} from './world-designer-coordinator-factories.js';
import { createWorldDesignerEntityConversion } from '../entities/world-designer-entity-conversion.js';
import { createWorldDesignerInteractionHandlers } from '../interaction/world-designer-interaction-handlers.js';
import { createWorldDesignerLifecycleController } from '../lifecycle/world-designer-lifecycle-controller.js';
import { createWorldDesignerPanelRefreshController } from '../panel/world-designer-panel-refresh-controller.js';
import { createWorldDesignerPreviewRenderingController } from '../preview/world-designer-preview-rendering-controller.js';
import { initializeWorldDesignerRuntimeAssembly } from '../runtime/world-designer-runtime-assembly.js';

export function initializeInteractionCoordinator(context: any) {
    return createInteractionCoordinatorFromContext({
        state: context.state,
        host: context.host,
        refs: context.refs,
        spriteTypes: context.spriteTypes,
        historyLimit: context.historyLimit,
        paletteCount: context.paletteCount,
        clipboardEntries: context.clipboardEntriesRef.get(),
        getCategoryArray: context.getCategoryArray,
        getTeleporters: context.teleporterApi.getTeleporters,
        findTeleporterForWorldBlock: context.teleporterApi.findTeleporterForWorldBlock,
        getButtons: context.getButtons,
        runMutation: context.runMutation,
        normalizeRotation: context.normalizeRotation,
        normalizeSpriteTranslation: context.normalizeSpriteTranslation,
        categorySupportsTranslation: context.categorySupportsTranslation,
        refreshPanel: context.refreshPanel,
        persistDesignerUiState: context.persistDesignerUiState,
        setStatus: context.setStatus,
        getSelectionBounds: context.selectionGeometry.getSelectionBounds,
        findWorldBlockByExactPosition: context.teleporterApi.findWorldBlockByExactPosition,
        serializeSelectionEntity: context.serializeSelectionEntity,
        createPastedSelections: context.createPastedSelections,
        applyEntityRotationWithTeleporterSync: context.teleporterApi.applyEntityRotationWithTeleporterSync,
        applyEntityPositionWithTeleporterSync: context.teleporterApi.applyEntityPositionWithTeleporterSync,
        getClipboardEntries: context.clipboardEntriesRef.get,
        setClipboardEntries: context.clipboardEntriesRef.set,
        getSnapshot: context.getSnapshot,
        deepClone: context.deepClone,
        getCustomSpriteDefinitionById: context.getCustomSpriteDefinitionById,
        invalidateOverviewBase: context.invalidateOverviewBase,
        updateDirtyState: context.updateDirtyState,
        syncEditModeSnapshot: context.syncEditModeSnapshot,
        getCurrentType: context.getCurrentType,
        getRectAtPosition: context.geometry.getRectAtPosition,
        getEntityRect: context.geometry.getEntityRect,
        getHitCandidates: context.selectionGeometry.getHitCandidates,
        screenToWorld: context.screenToWorld,
        snapshotsEqual: context.designerSnapshotsEqual,
        isTeleporterCompositeType: context.isTeleporterCompositeType,
        isButtonCompositeType: context.isButtonCompositeType,
        createTeleporterCompositeAt: context.teleporterApi.createTeleporterCompositeAt,
        createButtonEntity: context.createButtonEntity,
        createCustomSpriteInstance: context.createCustomSpriteInstance,
        createDoorEntity: context.createDoorEntity,
        createCreatureEntity: context.createCreatureEntity,
        createCollectableEntity: context.createCollectableEntity,
        getDefaultCollectableWeight: context.getDefaultCollectableWeight,
        getDefaultCollectablePaletteCycle: context.getDefaultCollectablePaletteCycle,
        getPaletteCount: context.getPaletteCount,
        playMushroomPlacementSound: context.playMushroomPlacementSound,
        clamp: context.clamp,
        renderSpritePreviewCanvas: context.renderSpritePreviewCanvas,
        updateSelectionFromInspectorState: context.updateSelectionFromInspectorState,
        getCanvasPoint: context.getCanvasPoint,
        canGroupSelections: context.canGroupSelections,
        groupSelectionsAsCustomSprite: context.groupSelectionsAsCustomSprite,
        ungroupCustomSpriteSelection: context.ungroupCustomSpriteSelection,
        deleteCustomSpriteSelectionDefinition: context.deleteCustomSpriteSelectionDefinition,
        shouldMaskAstronaut: context.shouldMaskAstronaut,
        convertSelectionToCategory: context.convertSelectionToCategory,
        getContextMenuSelectedTeleporterPair: context.teleporterApi.getContextMenuSelectedTeleporterPair,
        convertTeleporterWorldPair: context.teleporterApi.convertTeleporterWorldPair,
        canConvertCustomSpriteToButton: context.canConvertCustomSpriteToButton
    });
}

export function initializePanelRefreshController(context: any) {
    return createWorldDesignerPanelRefreshController({
        refs: context.refs,
        state: context.state,
        host: context.host,
        paletteCount: context.paletteCount,
        spriteTypes: context.spriteTypes,
        getSingleEditableSelection: context.getSingleEditableSelection,
        getPlacementTypeOptions: context.getPlacementTypeOptions,
        formatSpriteTranslation: context.formatSpriteTranslation,
        categorySupportsTranslation: context.categorySupportsTranslation,
        getCurrentType: context.getCurrentType,
        setCurrentType: context.setCurrentType,
        renderCurrentSpritePreview: context.renderCurrentSpritePreview,
        renderSpritePickerGrid: context.renderSpritePickerGrid,
        updateSelectionSummary: context.updateSelectionSummary,
        refreshInspector: context.refreshInspector,
        restorePendingInspectorFocus: context.restorePendingInspectorFocus,
        refreshPaletteDesigner: context.refreshPaletteDesigner,
        refreshStatus: context.refreshStatus,
        persistDesignerUiState: context.persistDesignerUiState
    });
}

export function initializePreviewRenderingController(context: any) {
    return createWorldDesignerPreviewRenderingController({
        tileSize: context.tileSize,
        host: context.host,
        refs: context.refs,
        state: context.state,
        getSelectedItems: context.getSelectedItems,
        getCurrentType: context.getCurrentType,
        isButtonCompositeType: context.isButtonCompositeType,
        isTeleporterCompositeType: context.isTeleporterCompositeType,
        createButtonEntity: context.createButtonEntity,
        getCustomSpriteDefinitionById: context.getCustomSpriteDefinitionById,
        getPlacementPreviewType: context.getPlacementPreviewType,
        categorySupportsTranslation: context.categorySupportsTranslation,
        formatSpriteTranslation: context.formatSpriteTranslation,
        normalizeRotation: context.normalizeRotation,
        normalizeSpriteTranslation: context.normalizeSpriteTranslation,
        getEntityRect: context.getEntityRect,
        getRectAtPosition: context.getRectAtPosition,
        deepClone: context.deepClone,
        renderSpritePreviewCanvas: context.renderSpritePreviewCanvas,
        renderButtonCompositePreviewCanvas: context.renderButtonCompositePreviewCanvas
    });
}

export function initializeEntityConversionApi(context: any) {
    return createWorldDesignerEntityConversion({
        state: context.state,
        spriteTypes: context.spriteTypes,
        categoryLabels: context.categoryLabels,
        buttonDefaultPressOffset: context.buttonDefaultPressOffset,
        buttonDefaultBoxOffsetX: context.buttonDefaultBoxOffsetX,
        buttonDefaultBoxOffsetY: context.buttonDefaultBoxOffsetY,
        getPaletteCount: context.getPaletteCount,
        getCategoryArray: context.getCategoryArray,
        setSelections: context.setSelections,
        getCustomSpriteDefinitionForInstance: context.getCustomSpriteDefinitionForInstance,
        getNextDoorId: context.getNextDoorId,
        normalizeRotation: context.normalizeRotation,
        normalizeSpriteTranslation: context.normalizeSpriteTranslation,
        categorySupportsTranslation: context.categorySupportsTranslation,
        getDoorTypeFromSourceType: context.getDoorTypeFromSourceType,
        invertButtonOffset: context.invertButtonOffset,
        deepClone: context.deepClone,
        getDefaultCollectableWeight: context.getDefaultCollectableWeight,
        getDefaultCollectablePaletteCycle: context.getDefaultCollectablePaletteCycle,
        getDefaultDestructibleEnabled: context.getDefaultDestructibleEnabled,
        getDefaultDestructibleHealth: context.getDefaultDestructibleHealth,
        getDefaultDestructionSource: context.getDefaultDestructionSource
    });
}

export function initializeInteractionHandlers(context: any) {
    return createWorldDesignerInteractionHandlers({
        state: context.state,
        refs: context.refs,
        host: context.host,
        mapWidth: context.mapWidth,
        mapHeight: context.mapHeight,
        clamp: context.clamp,
        isFormTarget: context.isFormTarget,
        getCanvasPoint: context.getCanvasPoint,
        closeContextMenu: context.closeContextMenu,
        screenToWorld: context.screenToWorld,
        getTeleporterById: context.getTeleporterById,
        runMutation: context.runMutation,
        setStatus: context.setStatus,
        getEntityAt: context.getEntityAt,
        isSelected: context.isSelected,
        getSelectedItems: context.getSelectedItems,
        setSelections: context.setSelections,
        removeSelection: context.removeSelection,
        areSameSelection: context.areSameSelection,
        mergeSelections: context.mergeSelections,
        updateModifierSnapMode: context.updateModifierSnapMode,
        placeAtWorld: context.placeAtWorld,
        updateSelectionFromInspectorState: context.updateSelectionFromInspectorState,
        categoryLabels: context.categoryLabels,
        beginDrag: context.beginDrag,
        updateDraggedItems: context.updateDraggedItems,
        placeDraggedPickerSprite: context.placeDraggedPickerSprite,
        clearPickerDrag: context.clearPickerDrag,
        persistDesignerUiState: context.persistDesignerUiState,
        getSelectionsInRect: context.getSelectionsInRect,
        completeDrag: context.completeDrag,
        setDesignerActive: context.setDesignerActive,
        refreshModifierSnapInteraction: context.refreshModifierSnapInteraction,
        closeModal: context.closeModal,
        openSavePreview: context.openSavePreview,
        undo: context.undo,
        redo: context.redo,
        duplicateSelection: context.duplicateSelection,
        copySelection: context.copySelection,
        pasteSelection: context.pasteSelection,
        refreshPanel: context.refreshPanel,
        restoreEditModeSnapshot: context.restoreEditModeSnapshot,
        deleteSelection: context.deleteSelection,
        rotateSelection: context.rotateSelection,
        nudgeSelection: context.nudgeSelection
    });
}

export function initializeLifecycleController(context: any) {
    return createWorldDesignerLifecycleController({
        state: context.state,
        host: context.host,
        initialCanvasStyle: context.initialCanvasStyle,
        initialCanvasSize: context.initialCanvasSize,
        initialBodyOverflow: context.initialBodyOverflow,
        setStatus: context.setStatus,
        refreshPanel: context.refreshPanel,
        syncEditModeSnapshot: context.syncEditModeSnapshot,
        focusOnCurrentWorldPosition: context.focusOnCurrentWorldPosition,
        closeContextMenu: context.closeContextMenu,
        closeModal: context.closeModal
    });
}

export function initializeModalCoordinator(context: any) {
    return createModalCoordinatorFromContext({
        refs: context.refs,
        state: context.state,
        host: context.host,
        spriteTypes: context.spriteTypes,
        paletteCount: context.paletteCount,
        clearPngImportObjectUrl: context.clearPngImportObjectUrl,
        getPaletteCount: context.getPaletteCount,
        getAuthoredWorldSnapshot: context.getAuthoredWorldSnapshot,
        getWorldSnapshotForValidationAndSave: context.getWorldSnapshotForValidationAndSave,
        stableStringify: context.stableStringify,
        snapshotsEqual: context.snapshotsEqual,
        paletteDefinitionsEqual: context.paletteDefinitionsEqual,
        deepClone: context.deepClone,
        serializeWorldData: context.serializeWorldData,
        syncPaletteCount: context.syncPaletteCount,
        refreshSelectOptions: context.refreshSelectOptions,
        refreshPaletteDesigner: context.refreshPaletteDesigner,
        syncEditModeSnapshot: context.syncEditModeSnapshot,
        updateDirtyState: context.updateDirtyState,
        setStatus: context.setStatus,
        refreshPanel: context.refreshPanel,
        PNG_IMPORT_DEFAULT_URL: context.constants.PNG_IMPORT_DEFAULT_URL,
        PNG_IMPORT_SOURCE_TILE_SIZE: context.constants.PNG_IMPORT_SOURCE_TILE_SIZE,
        PNG_CHUNK_EXPORT_MANIFEST_NAME: context.constants.PNG_CHUNK_EXPORT_MANIFEST_NAME,
        PNG_CHUNK_DEFAULT_TILE_WIDTH: context.constants.PNG_CHUNK_DEFAULT_TILE_WIDTH,
        PNG_CHUNK_DEFAULT_TILE_HEIGHT: context.constants.PNG_CHUNK_DEFAULT_TILE_HEIGHT,
        PNG_IMPORT_PREVIEW_MAX_TILE_SIZE: context.constants.PNG_IMPORT_PREVIEW_MAX_TILE_SIZE,
        SPRITE_TRANSLATION_OPTIONS: context.SPRITE_TRANSLATION_OPTIONS,
        formatSpriteTranslation: context.formatSpriteTranslation,
        getDefaultImportWorldRect: context.getDefaultImportWorldRect,
        getPngImportTypeNames: context.getPngImportTypeNames,
        getPngImportTypeDefaults: context.getPngImportTypeDefaults,
        setPngImportObjectUrl: context.setPngImportObjectUrl,
        clamp: context.clamp,
        getPngChunkSelectionEntries: context.getPngChunkSelectionEntries,
        getPngImportWorldSpanFromTileCount: context.getPngImportWorldSpanFromTileCount,
        composePngChunkFolderSource: context.composePngChunkFolderSource,
        pngImportDraftApi: context.pngImportDraftApi,
        normalizeRotation: context.normalizeRotation,
        normalizeSpriteTranslation: context.normalizeSpriteTranslation,
        renderSpritePreviewCanvas: context.renderSpritePreviewCanvas,
        clearPreviewCanvas: context.clearPreviewCanvas,
        getPngImportSourceTileCount: context.getPngImportSourceTileCount,
        getSuggestedPngImportWorldSpan: context.getSuggestedPngImportWorldSpan,
        getDirectoryPicker: context.getDirectoryPicker,
        readPngChunkFolderSelection: context.readPngChunkFolderSelection,
        exportPngChunksToDirectory: context.exportPngChunksToDirectory,
        toMapBlockData: context.toMapBlockData,
        applyPngImportDraft: context.applyPngImportDraft
    });
}

export function initializeInspectorCoordinator(context: any) {
    return createInspectorCoordinatorFromContext({
        refs: context.refs,
        state: context.state,
        host: context.host,
        paletteCount: context.paletteCount,
        spriteTypes: context.spriteTypes,
        CATEGORY_LABELS: context.constants.CATEGORY_LABELS,
        SPRITE_TRANSLATION_OPTIONS: context.SPRITE_TRANSLATION_OPTIONS,
        BUTTON_DEFAULT_PRESS_OFFSET: context.constants.BUTTON_DEFAULT_PRESS_OFFSET,
        BUTTON_DEFAULT_BOX_OFFSET_X: context.constants.BUTTON_DEFAULT_BOX_OFFSET_X,
        BUTTON_DEFAULT_BOX_OFFSET_Y: context.constants.BUTTON_DEFAULT_BOX_OFFSET_Y,
        MOVEMENT_SETTINGS: context.MOVEMENT_SETTINGS,
        DESTRUCTION_SOURCE_OPTIONS: context.DESTRUCTION_SOURCE_OPTIONS,
        CREATURE_SOUND_MANIFEST: context.CREATURE_SOUND_MANIFEST,
        getSelectedItems: context.getSelectedItems,
        getAstronautStartPosition: context.getAstronautStartPosition,
        getConvertTargetCategories: context.getConvertTargetCategories,
        getEffectiveButtonDefaultOverrides: context.getEffectiveButtonDefaultOverrides,
        runMutation: context.runMutation,
        clamp: context.clamp,
        setButtonDefaultOverridesFromButton: context.setButtonDefaultOverridesFromButton,
        resetButtonDefaultOverrides: context.resetButtonDefaultOverrides,
        getCustomSpriteDefinitionForInstance: context.getCustomSpriteDefinitionForInstance,
        createCustomSpriteName: context.createCustomSpriteName,
        renameCustomSpriteDefinition: context.renameCustomSpriteDefinition,
        deleteCustomSpriteSelectionDefinition: context.deleteCustomSpriteSelectionDefinition,
        applyEntityPositionWithTeleporterSync: context.applyEntityPositionWithTeleporterSync,
        applyEntityRotationWithTeleporterSync: context.applyEntityRotationWithTeleporterSync,
        normalizeRotation: context.normalizeRotation,
        categorySupportsTranslation: context.categorySupportsTranslation,
        normalizeSpriteTranslation: context.normalizeSpriteTranslation,
        getEffectivePaletteCycle: context.getEffectivePaletteCycle,
        buildDefaultPaletteCycle: context.buildDefaultPaletteCycle,
        parsePaletteCyclePalettes: context.parsePaletteCyclePalettes,
        shouldMaskAstronaut: context.shouldMaskAstronaut,
        findTeleporterForWorldBlock: context.findTeleporterForWorldBlock,
        convertWorldTeleporterBlock: context.convertWorldTeleporterBlock,
        renameTeleporterId: context.renameTeleporterId,
        setStatus: context.setStatus,
        getDefaultDestructibleEnabled: context.getDefaultDestructibleEnabled,
        getDefaultDestructibleHealth: context.getDefaultDestructibleHealth,
        getDefaultDestructionSource: context.getDefaultDestructionSource,
        parseDoorIds: context.parseDoorIds,
        parseStringIds: context.parseStringIds,
        isTeleporterMode: context.isTeleporterMode,
        getButtonCapOffsetsRelativeToBox: context.getButtonCapOffsetsRelativeToBox,
        stableStringify: context.stableStringify,
        getDefaultCollectableWeight: context.getDefaultCollectableWeight,
        getDefaultCollectablePaletteCycle: context.getDefaultCollectablePaletteCycle,
        isGrenadeCollectableType: context.isGrenadeCollectableType,
        getDefaultGrenadeExplosionPower: context.getDefaultGrenadeExplosionPower,
        pendingInspectorFocusRef: context.pendingInspectorFocusRef
    });
}

export function initializeRuntimeAssembly(context: any) {
    return initializeWorldDesignerRuntimeAssembly({
        refs: context.refs,
        state: context.state,
        host: context.host,
        paletteCount: context.paletteCount,
        colorAliasNames: context.colorAliasNames,
        CATEGORY_LABELS: context.constants.CATEGORY_LABELS,
        clamp: context.clamp,
        normalizeRotation: context.normalizeRotation,
        normalizeSpriteTranslation: context.normalizeSpriteTranslation,
        categorySupportsTranslation: context.categorySupportsTranslation,
        isTeleporterCompositeType: context.isTeleporterCompositeType,
        isButtonCompositeType: context.isButtonCompositeType,
        getSingleEditableSelection: context.getSingleEditableSelection,
        getCustomSpriteDefinitionById: context.getCustomSpriteDefinitionById,
        runMutation: context.runMutation,
        updateSelectionFromInspectorState: context.updateSelectionFromInspectorState,
        setCurrentType: context.setCurrentType,
        renderSpritePickerGrid: context.renderSpritePickerGrid,
        persistDesignerUiState: context.persistDesignerUiState,
        applyEntityRotationWithTeleporterSync: context.applyEntityRotationWithTeleporterSync,
        renderCurrentSpritePreview: context.renderCurrentSpritePreview,
        refreshModifierSnapInteraction: context.refreshModifierSnapInteraction,
        setSnapOffsets: context.setSnapOffsets,
        setSnapOffsetsFromPosition: context.setSnapOffsetsFromPosition,
        setStatus: context.setStatus,
        invalidateOverviewBase: context.invalidateOverviewBase,
        setDesignerActive: context.setDesignerActive,
        createNewPalette: context.createNewPalette,
        cloneSelectedPalette: context.cloneSelectedPalette,
        deleteSelectedPalette: context.deleteSelectedPalette,
        savePaletteDesigner: context.savePaletteDesigner,
        restoreEditModeSnapshot: context.restoreEditModeSnapshot,
        refreshPaletteDesigner: context.refreshPaletteDesigner,
        openSavePreview: context.openSavePreview,
        openPngImportModal: context.openPngImportModal,
        openSpriteSheetNormalizationPreview: context.openSpriteSheetNormalizationPreview,
        closeModal: context.closeModal,
        modalCoordinator: context.modalCoordinator,
        convertSelection: context.convertSelection,
        focusOnCurrentWorldPosition: context.focusOnCurrentWorldPosition,
        moveLiveAstronautToViewCenter: context.moveLiveAstronautToViewCenter,
        setAstronautStartToViewCenter: context.setAstronautStartToViewCenter,
        getCanvasPoint: context.getCanvasPoint,
        screenToWorld: context.screenToWorld,
        getEntityAt: context.getEntityAt,
        interactionHandlers: context.interactionHandlers,
        selectionApi: context.selectionApi,
        restoredViewportExpanded: context.restoredViewportExpanded,
        overviewBaseCanvas: context.overviewBaseCanvas,
        mapWidth: context.constants.MAP_WIDTH,
        mapHeight: context.constants.MAP_HEIGHT,
        tileSize: context.constants.TILE_SIZE,
        getChunkedWorldOverview: context.getChunkedWorldOverview,
        getCategoryArray: context.getCategoryArray,
        getEntityRect: context.getEntityRect,
        getAstronautStartPosition: context.getAstronautStartPosition,
        ensureOverviewWorldTilesLoaded: context.ensureOverviewWorldTilesLoaded,
        getOverviewWorldTiles: context.getOverviewWorldTiles,
        getSelectionVisuals: context.getSelectionVisuals,
        drawCustomSpriteDefinitionAt: context.drawCustomSpriteDefinitionAt,
        getCustomSpriteDefinitionForInstance: context.getCustomSpriteDefinitionForInstance,
        normalizeRect: context.normalizeRect,
        dragGhostCanvas: context.dragGhostCanvas,
        dragGhostPadding: context.dragGhostPadding,
        dragGhostTargetSize: context.dragGhostTargetSize,
        renderCustomSpritePreviewCanvas: context.renderCustomSpritePreviewCanvas,
        renderButtonCompositePreviewCanvas: context.renderButtonCompositePreviewCanvas,
        createButtonEntity: context.createButtonEntity,
        getPlacementPreviewType: context.getPlacementPreviewType,
        getTeleporterBaseRotationForPadRotation: context.getTeleporterBaseRotationForPadRotation,
        drawMagnifier: context.drawMagnifier,
        resetSpriteResolversAndCache: context.resetSpriteResolversAndCache,
        styles: context.styles,
        resizeExpandedViewport: context.resizeExpandedViewport,
        applyDesignerOverlayZoomCompensation: context.applyDesignerOverlayZoomCompensation,
        setViewportExpanded: context.setViewportExpanded,
        refreshSelectOptions: context.refreshSelectOptions,
        refreshPanel: context.refreshPanel,
        setRenderLifecycle: context.setRenderLifecycle,
        getRenderLifecycle: context.getRenderLifecycle,
        pendingOverviewBaseInvalidationRef: context.pendingOverviewBaseInvalidationRef
    });
}
