import { createWorldDesignerRenderLifecycle } from '../render/world-designer-render-lifecycle.js';

export function createRenderLifecycleFromContext(context: any) {
    return createWorldDesignerRenderLifecycle({
        overviewBaseCanvas: context.overviewBaseCanvas,
        refs: context.refs,
        state: context.state,
        host: context.host,
        getMapBounds: context.getMapBounds,
        tileSize: context.tileSize,
        getChunkedWorldOverview: context.getChunkedWorldOverview,
        getCategoryArray: context.getCategoryArray,
        getEntityRect: context.getEntityRect,
        getAstronautStartPosition: context.getAstronautStartPosition,
        ensureOverviewWorldTilesLoaded: context.ensureOverviewWorldTilesLoaded,
        getOverviewWorldTiles: context.getOverviewWorldTiles,
        getSelectionVisuals: context.getSelectionVisuals,
        getSelectedItems: context.getSelectedItems,
        drawCustomSpriteDefinitionAt: context.drawCustomSpriteDefinitionAt,
        getCustomSpriteDefinitionForInstance: context.getCustomSpriteDefinitionForInstance,
        normalizeRect: context.normalizeRect,
        getAutoPanDelta: context.getAutoPanDelta,
        updateDraggedItems: context.updateDraggedItems,
        screenToWorld: context.screenToWorld,
        resolvePlacementPosition: context.resolvePlacementPosition,
        dragGhostCanvas: context.dragGhostCanvas,
        dragGhostPadding: context.dragGhostPadding,
        dragGhostTargetSize: context.dragGhostTargetSize,
        renderCustomSpritePreviewCanvas: context.renderCustomSpritePreviewCanvas,
        getCustomSpriteDefinitionById: context.getCustomSpriteDefinitionById,
        isButtonCompositeType: context.isButtonCompositeType,
        renderButtonCompositePreviewCanvas: context.renderButtonCompositePreviewCanvas,
        createButtonEntity: context.createButtonEntity,
        getPlacementPreviewType: context.getPlacementPreviewType,
        isTeleporterCompositeType: context.isTeleporterCompositeType,
        getTeleporterBaseRotationForPadRotation: context.getTeleporterBaseRotationForPadRotation,
        drawMagnifier: context.drawMagnifier,
        setViewportExpanded: context.setViewportExpanded,
        resetSpriteResolversAndCache: context.resetSpriteResolversAndCache,
        closeContextMenu: context.closeContextMenu,
        eventHandlers: context.eventHandlers,
        styles: context.styles
    });
}
