import { createWorldDesignerInteractionCoordinator } from '../coordinator/world-designer-interaction-coordinator.js';
import { createWorldDesignerModalCoordinator } from '../modal/world-designer-modal-coordinator.js';
import { createWorldDesignerInspectorCoordinator } from '../inspector/world-designer-inspector-coordinator.js';

export function createInteractionCoordinatorFromContext(context: any) {
    return createWorldDesignerInteractionCoordinator({
        selectionOrderingDeps: {
            getCategoryArray: context.getCategoryArray,
            getTeleporters: context.getTeleporters,
            findTeleporterForWorldBlock: context.findTeleporterForWorldBlock,
            getButtons: context.getButtons,
            runMutation: context.runMutation
        },
        selectionActionsDeps: {
            state: context.state,
            host: context.host,
            spriteTypes: context.spriteTypes,
            normalizeRotation: context.normalizeRotation,
            normalizeSpriteTranslation: context.normalizeSpriteTranslation,
            categorySupportsTranslation: context.categorySupportsTranslation,
            refreshPanel: context.refreshPanel,
            persistDesignerUiState: context.persistDesignerUiState,
            setStatus: context.setStatus,
            getSelectionBounds: context.getSelectionBounds,
            getCategoryArray: context.getCategoryArray,
            findTeleporterForWorldBlock: context.findTeleporterForWorldBlock,
            findWorldBlockByExactPosition: context.findWorldBlockByExactPosition,
            serializeSelectionEntity: context.serializeSelectionEntity,
            createPastedSelections: context.createPastedSelections,
            runMutation: context.runMutation,
            applyEntityRotationWithTeleporterSync: context.applyEntityRotationWithTeleporterSync,
            applyEntityPositionWithTeleporterSync: context.applyEntityPositionWithTeleporterSync,
            getClipboardEntries: context.getClipboardEntries,
            setClipboardEntries: context.setClipboardEntries,
            getSnapshot: context.getSnapshot,
            deepClone: context.deepClone,
            getCustomSpriteDefinitionById: context.getCustomSpriteDefinitionById,
            invalidateOverviewBase: context.invalidateOverviewBase,
            updateDirtyState: context.updateDirtyState,
            syncEditModeSnapshot: context.syncEditModeSnapshot
        },
        placementDeps: {
            state: context.state,
            historyLimit: context.historyLimit,
            host: context.host,
            getCurrentType: context.getCurrentType,
            getCategoryArray: context.getCategoryArray,
            getRectAtPosition: context.getRectAtPosition,
            getEntityRect: context.getEntityRect,
            getHitCandidates: context.getHitCandidates,
            getSnapshot: context.getSnapshot,
            applyEntityPositionWithTeleporterSync: context.applyEntityPositionWithTeleporterSync,
            screenToWorld: context.screenToWorld,
            refreshPanel: context.refreshPanel,
            updateDirtyState: context.updateDirtyState,
            setStatus: context.setStatus,
            snapshotsEqual: context.snapshotsEqual,
            isTeleporterCompositeType: context.isTeleporterCompositeType,
            isButtonCompositeType: context.isButtonCompositeType,
            createTeleporterCompositeAt: context.createTeleporterCompositeAt,
            createButtonEntity: context.createButtonEntity,
            getCustomSpriteDefinitionById: context.getCustomSpriteDefinitionById,
            createCustomSpriteInstance: context.createCustomSpriteInstance,
            createDoorEntity: context.createDoorEntity,
            createCreatureEntity: context.createCreatureEntity,
            createCollectableEntity: context.createCollectableEntity,
            getDefaultCollectableWeight: context.getDefaultCollectableWeight,
            getDefaultCollectablePaletteCycle: context.getDefaultCollectablePaletteCycle,
            getPaletteCount: context.getPaletteCount,
            playMushroomPlacementSound: context.playMushroomPlacementSound
        },
        contextMenuDeps: {
            state: context.state,
            refs: {
                contextMenu: context.refs.contextMenu,
                contextMenuBody: context.refs.contextMenuBody
            },
            paletteCount: context.paletteCount,
            clipboardEntries: context.clipboardEntries,
            host: context.host,
            clamp: context.clamp,
            normalizeRotation: context.normalizeRotation,
            normalizeSpriteTranslation: context.normalizeSpriteTranslation,
            renderSpritePreviewCanvas: context.renderSpritePreviewCanvas,
            runMutation: context.runMutation,
            updateSelectionFromInspectorState: context.updateSelectionFromInspectorState,
            setStatus: context.setStatus,
            screenToWorld: context.screenToWorld,
            getCanvasPoint: context.getCanvasPoint,
            getCurrentType: context.getCurrentType,
            canGroupSelections: context.canGroupSelections,
            groupSelectionsAsCustomSprite: context.groupSelectionsAsCustomSprite,
            ungroupCustomSpriteSelection: context.ungroupCustomSpriteSelection,
            deleteCustomSpriteSelectionDefinition: context.deleteCustomSpriteSelectionDefinition,
            shouldMaskAstronaut: context.shouldMaskAstronaut,
            convertSelectionToCategory: context.convertSelectionToCategory,
            getContextMenuSelectedTeleporterPair: context.getContextMenuSelectedTeleporterPair,
            convertTeleporterWorldPair: context.convertTeleporterWorldPair,
            canConvertCustomSpriteToButton: context.canConvertCustomSpriteToButton,
            createPastedSelections: context.createPastedSelections
        }
    });
}

export function createModalCoordinatorFromContext(context: any) {
    return createWorldDesignerModalCoordinator({
        modalControllerDeps: {
            refs: {
                modal: context.refs.modal,
                modalConfirm: context.refs.modalConfirm
            },
            state: context.state,
            clearPngImportObjectUrl: context.clearPngImportObjectUrl
        },
        saveWorkflowDeps: {
            refs: context.refs,
            state: context.state,
            host: context.host,
            spriteTypes: context.spriteTypes,
            getPaletteCount: context.getPaletteCount,
            getAuthoredWorldSnapshot: context.getAuthoredWorldSnapshot,
            getWorldSnapshotForValidationAndSave: context.getWorldSnapshotForValidationAndSave,
            stableStringify: context.stableStringify,
            snapshotsEqual: context.snapshotsEqual,
            paletteDefinitionsEqual: context.paletteDefinitionsEqual,
            deepClone: context.deepClone,
            serializeWorldData: context.serializeWorldData,
            syncPaletteCount: context.syncPaletteCount,
            refreshSelectOptions: context.refreshSelectOptions,
            refreshPaletteDesigner: context.refreshPaletteDesigner,
            syncEditModeSnapshot: context.syncEditModeSnapshot,
            updateDirtyState: context.updateDirtyState,
            setStatus: context.setStatus,
            refreshPanel: context.refreshPanel
        },
        pngImportModalDeps: {
            refs: context.refs,
            host: context.host,
            paletteCount: context.paletteCount,
            PNG_IMPORT_DEFAULT_URL: context.PNG_IMPORT_DEFAULT_URL,
            PNG_IMPORT_SOURCE_TILE_SIZE: context.PNG_IMPORT_SOURCE_TILE_SIZE,
            PNG_CHUNK_EXPORT_MANIFEST_NAME: context.PNG_CHUNK_EXPORT_MANIFEST_NAME,
            PNG_CHUNK_DEFAULT_TILE_WIDTH: context.PNG_CHUNK_DEFAULT_TILE_WIDTH,
            PNG_CHUNK_DEFAULT_TILE_HEIGHT: context.PNG_CHUNK_DEFAULT_TILE_HEIGHT,
            PNG_IMPORT_PREVIEW_MAX_TILE_SIZE: context.PNG_IMPORT_PREVIEW_MAX_TILE_SIZE,
            SPRITE_TRANSLATION_OPTIONS: context.SPRITE_TRANSLATION_OPTIONS,
            formatSpriteTranslation: context.formatSpriteTranslation,
            getDefaultImportWorldRect: context.getDefaultImportWorldRect,
            getPngImportTypeNames: context.getPngImportTypeNames,
            getPngImportTypeDefaults: context.getPngImportTypeDefaults,
            clearPngImportObjectUrl: context.clearPngImportObjectUrl,
            setPngImportObjectUrl: context.setPngImportObjectUrl,
            setStatus: context.setStatus,
            clamp: context.clamp,
            getPngChunkSelectionEntries: context.getPngChunkSelectionEntries,
            getPngImportWorldSpanFromTileCount: context.getPngImportWorldSpanFromTileCount,
            composePngChunkFolderSource: context.composePngChunkFolderSource,
            pngImportDraftApi: context.pngImportDraftApi,
            normalizeRotation: context.normalizeRotation,
            normalizeSpriteTranslation: context.normalizeSpriteTranslation,
            renderSpritePreviewCanvas: context.renderSpritePreviewCanvas,
            clearPreviewCanvas: context.clearPreviewCanvas,
            getPngImportSourceTileCount: context.getPngImportSourceTileCount,
            getSuggestedPngImportWorldSpan: context.getSuggestedPngImportWorldSpan,
            getDirectoryPicker: context.getDirectoryPicker,
            readPngChunkFolderSelection: context.readPngChunkFolderSelection,
            exportPngChunksToDirectory: context.exportPngChunksToDirectory,
            toMapBlockData: context.toMapBlockData,
            applyPngImportDraft: context.applyPngImportDraft
        }
    });
}

export function createInspectorCoordinatorFromContext(context: any) {
    return createWorldDesignerInspectorCoordinator({
        panelDeps: {
            refs: context.refs,
            state: context.state,
            host: context.host,
            paletteCount: context.paletteCount,
            spriteTypes: context.spriteTypes,
            CATEGORY_LABELS: context.CATEGORY_LABELS,
            SPRITE_TRANSLATION_OPTIONS: context.SPRITE_TRANSLATION_OPTIONS,
            BUTTON_DEFAULT_PRESS_OFFSET: context.BUTTON_DEFAULT_PRESS_OFFSET,
            BUTTON_DEFAULT_BOX_OFFSET_X: context.BUTTON_DEFAULT_BOX_OFFSET_X,
            BUTTON_DEFAULT_BOX_OFFSET_Y: context.BUTTON_DEFAULT_BOX_OFFSET_Y,
            MOVEMENT_SETTINGS: context.MOVEMENT_SETTINGS,
            DESTRUCTION_SOURCE_OPTIONS: context.DESTRUCTION_SOURCE_OPTIONS,
            CREATURE_SOUND_MANIFEST: context.CREATURE_SOUND_MANIFEST,
            getSelectedItems: context.getSelectedItems,
            getAstronautStartPosition: context.getAstronautStartPosition,
            getConvertTargetCategories: context.getConvertTargetCategories,
            getEffectiveButtonDefaultOverrides: context.getEffectiveButtonDefaultOverrides,
            runMutation: context.runMutation,
            clamp: context.clamp,
            setButtonDefaultOverridesFromButton: context.setButtonDefaultOverridesFromButton,
            resetButtonDefaultOverrides: context.resetButtonDefaultOverrides,
            getCustomSpriteDefinitionForInstance: context.getCustomSpriteDefinitionForInstance,
            createCustomSpriteName: context.createCustomSpriteName,
            renameCustomSpriteDefinition: context.renameCustomSpriteDefinition,
            deleteCustomSpriteSelectionDefinition: context.deleteCustomSpriteSelectionDefinition,
            applyEntityPositionWithTeleporterSync: context.applyEntityPositionWithTeleporterSync,
            applyEntityRotationWithTeleporterSync: context.applyEntityRotationWithTeleporterSync,
            normalizeRotation: context.normalizeRotation,
            categorySupportsTranslation: context.categorySupportsTranslation,
            normalizeSpriteTranslation: context.normalizeSpriteTranslation,
            getEffectivePaletteCycle: context.getEffectivePaletteCycle,
            buildDefaultPaletteCycle: context.buildDefaultPaletteCycle,
            parsePaletteCyclePalettes: context.parsePaletteCyclePalettes,
            shouldMaskAstronaut: context.shouldMaskAstronaut,
            findTeleporterForWorldBlock: context.findTeleporterForWorldBlock,
            convertWorldTeleporterBlock: context.convertWorldTeleporterBlock,
            renameTeleporterId: context.renameTeleporterId,
            setStatus: context.setStatus,
            getDefaultDestructibleEnabled: context.getDefaultDestructibleEnabled,
            getDefaultDestructibleHealth: context.getDefaultDestructibleHealth,
            getDefaultDestructionSource: context.getDefaultDestructionSource,
            parseDoorIds: context.parseDoorIds,
            parseStringIds: context.parseStringIds,
            isTeleporterMode: context.isTeleporterMode,
            getButtonCapOffsetsRelativeToBox: context.getButtonCapOffsetsRelativeToBox,
            stableStringify: context.stableStringify,
            getDefaultCollectableWeight: context.getDefaultCollectableWeight,
            getDefaultCollectablePaletteCycle: context.getDefaultCollectablePaletteCycle,
            isGrenadeCollectableType: context.isGrenadeCollectableType,
            getDefaultGrenadeExplosionPower: context.getDefaultGrenadeExplosionPower
        },
        inspectorRoot: context.refs.inspector,
        pendingInspectorFocusRef: context.pendingInspectorFocusRef
    });
}
