export const MOVEMENT_SETTINGS = {
    gravity: 0.035,
    groundedTakeoffImpulse: -0.8,
    headBounceRestitution: 0.35,
    headBounceMinImpactSpeed: 0.9,
    headBounceSlopeThreshold: 0.2,
    upAccel: -0.3,
    downAccel: 0.3,
    maxUpSpeed: -4,
    fallTerminalVelocity: 5.5,
    flyDownTerminalVelocity: 7.25,
    walkAccel: 0.3,
    walkMaxSpeed: 3,
    walkStartSpeed: 1,
    flyAccel: 0.28,
    flyMaxSpeed: 5.6,
    landingMomentumFactor: 0.65,
    landingMomentumMinSpeed: 0.35,
    walkStepUpHeight: 6,
    heldWeightIgnoreThreshold: 0.3,
    heldWeightWalkPenaltyPerUnit: 0.12,
    heldWeightFlyPenaltyPerUnit: 0.1,
    heldWeightGravityBonusPerUnit: 0.08,
    heldWeightTerminalVelocityBonusPerUnit: 0.12,
    heldWeightMinScale: 0.45,
    collectableGravity: 0.05,
    collectableTerminalVelocity: 6,
    collectableGroundSnapDistance: 3,
    collectableGroundFriction: 0.18,
    collectableBounceRestitution: 0.48,
    collectableBounceMinImpactSpeed: 0.35,
    collectableBounceWeightPenaltyPerUnit: 0.6,
    collectablePushVelocityMultiplier: 1.1,
    collectablePushMaxSpeed: 5,
    collectablePushResistancePerUnit: 0.35,
    collectablePushMinScale: 0.2,
    collectablePickupRange: 52,
    collectableInventoryLimit: 5,
    heldCollectableForwardOffset: 28,
    heldCollectableVerticalOffset: -6,
    droppedCollectableForwardOffset: 24,
    droppedCollectableAstronautIgnoreFrames: 18,
    droppedCollectableMomentumTransfer: 0.75,
    throwAngleAdjustDegreesPerFrame: 2.4,
    throwVelocity: 5.6,
    throwGuideDotSpeed: 14,
    throwGuideDotEmitIntervalFrames: 2,
    throwGuideDotsPerBurst: 2,
    throwGuideDotSize: 2.2
} as const;

export const VIEWPORT_SETTINGS = {
    defaultWidth: 1000,
    defaultHeight: 675
} as const;
