import {
    initializeEntityConversionApi,
    initializeInspectorCoordinator,
    initializeInteractionHandlers,
    initializeInteractionCoordinator,
    initializeLifecycleController,
    initializeModalCoordinator,
    initializePanelRefreshController,
    initializePreviewRenderingController,
    initializeRuntimeAssembly
} from '../factory/world-designer-initializers.js';

export function initializePanelRefreshControllerFromMain(context: any) {
    return initializePanelRefreshController({
        refs: context.core.refs,
        state: context.core.state,
        host: context.core.host,
        paletteCount: context.data.paletteCount,
        spriteTypes: context.core.spriteTypes,
        getSingleEditableSelection: context.selection.getSingleEditableSelection,
        getPlacementTypeOptions: context.selection.getPlacementTypeOptions,
        formatSpriteTranslation: context.utilities.formatSpriteTranslation,
        categorySupportsTranslation: context.utilities.categorySupportsTranslation,
        getCurrentType: context.data.getCurrentType,
        setCurrentType: context.data.setCurrentType,
        renderCurrentSpritePreview: context.rendering.renderCurrentSpritePreview,
        renderSpritePickerGrid: context.rendering.renderSpritePickerGrid,
        updateSelectionSummary: context.panel.updateSelectionSummary,
        refreshInspector: context.panel.refreshInspector,
        restorePendingInspectorFocus: context.panel.restorePendingInspectorFocus,
        refreshPaletteDesigner: context.palette.refreshPaletteDesigner,
        refreshStatus: context.panel.refreshStatus,
        persistDesignerUiState: context.panel.persistDesignerUiState
    });
}

export function initializePreviewRenderingControllerFromMain(context: any) {
    return initializePreviewRenderingController({
        tileSize: context.core.tileSize,
        host: context.core.host,
        refs: context.refs,
        state: context.core.state,
        getSelectedItems: context.selection.getSelectedItems,
        getCurrentType: context.data.getCurrentType,
        isButtonCompositeType: context.types.isButtonCompositeType,
        isTeleporterCompositeType: context.types.isTeleporterCompositeType,
        createButtonEntity: context.entityFactories.createButtonEntity,
        getCustomSpriteDefinitionById: context.customSprites.getCustomSpriteDefinitionById,
        getPlacementPreviewType: context.selection.getPlacementPreviewType,
        categorySupportsTranslation: context.utilities.categorySupportsTranslation,
        formatSpriteTranslation: context.utilities.formatSpriteTranslation,
        normalizeRotation: context.utilities.normalizeRotation,
        normalizeSpriteTranslation: context.utilities.normalizeSpriteTranslation,
        getEntityRect: context.geometry.getEntityRect,
        getRectAtPosition: context.geometry.getRectAtPosition,
        deepClone: context.utilities.deepClone,
        renderSpritePreviewCanvas: context.rendering.renderSpritePreviewCanvas,
        renderButtonCompositePreviewCanvas: context.rendering.renderButtonCompositePreviewCanvas
    });
}

export function initializeEntityConversionApiFromMain(context: any) {
    return initializeEntityConversionApi({
        state: context.core.state,
        spriteTypes: context.core.spriteTypes,
        categoryLabels: context.constants.CATEGORY_LABELS,
        buttonDefaultPressOffset: context.constants.BUTTON_DEFAULT_PRESS_OFFSET,
        buttonDefaultBoxOffsetX: context.constants.BUTTON_DEFAULT_BOX_OFFSET_X,
        buttonDefaultBoxOffsetY: context.constants.BUTTON_DEFAULT_BOX_OFFSET_Y,
        getPaletteCount: context.data.getPaletteCount,
        getCategoryArray: context.data.getCategoryArray,
        setSelections: context.selection.setSelections,
        getCustomSpriteDefinitionForInstance: context.customSprites.getCustomSpriteDefinitionForInstance,
        getNextDoorId: context.data.getNextDoorId,
        normalizeRotation: context.utilities.normalizeRotation,
        normalizeSpriteTranslation: context.utilities.normalizeSpriteTranslation,
        categorySupportsTranslation: context.utilities.categorySupportsTranslation,
        getDoorTypeFromSourceType: context.data.getDoorTypeFromSourceType,
        invertButtonOffset: context.utilities.invertButtonOffset,
        deepClone: context.utilities.deepClone,
        getDefaultCollectableWeight: context.defaults.getDefaultCollectableWeight,
        getDefaultCollectablePaletteCycle: context.defaults.getDefaultCollectablePaletteCycle,
        getDefaultDestructibleEnabled: context.defaults.getDefaultDestructibleEnabled,
        getDefaultDestructibleHealth: context.defaults.getDefaultDestructibleHealth,
        getDefaultDestructionSource: context.defaults.getDefaultDestructionSource
    });
}

export function initializeLifecycleControllerFromMain(context: any) {
    return initializeLifecycleController({
        state: context.core.state,
        host: context.core.host,
        initialCanvasStyle: context.initialState.initialCanvasStyle,
        initialCanvasSize: context.initialState.initialCanvasSize,
        initialBodyOverflow: context.initialState.initialBodyOverflow,
        setStatus: context.mutations.setStatus,
        refreshPanel: context.panel.refreshPanel,
        syncEditModeSnapshot: context.mutations.syncEditModeSnapshot,
        focusOnCurrentWorldPosition: context.interaction.focusOnCurrentWorldPosition,
        closeContextMenu: context.interaction.closeContextMenu,
        closeModal: context.modal.closeModal
    });
}

export function initializeInteractionHandlersFromMain(context: any) {
    return initializeInteractionHandlers({
        state: context.core.state,
        refs: context.core.refs,
        host: context.core.host,
        getMapBounds: context.data.getMapBounds,
        clamp: context.utilities.clamp,
        isFormTarget: context.types.isFormTarget,
        getCanvasPoint: context.geometry.getCanvasPoint,
        closeContextMenu: context.interaction.closeContextMenu,
        screenToWorld: context.geometry.screenToWorld,
        getTeleporterById: context.teleporters.getTeleporterById,
        runMutation: context.mutations.runMutation,
        setStatus: context.mutations.setStatus,
        getEntityAt: context.selection.getEntityAt,
        isSelected: context.selection.isSelected,
        getSelectedItems: context.selection.getSelectedItems,
        setSelections: context.selection.setSelections,
        removeSelection: context.selection.removeSelection,
        areSameSelection: context.selection.areSameSelection,
        mergeSelections: context.selection.mergeSelections,
        updateModifierSnapMode: context.interaction.updateModifierSnapMode,
        placeAtWorld: context.interaction.placeAtWorld,
        updateSelectionFromInspectorState: context.selection.updateSelectionFromInspectorState,
        categoryLabels: context.constants.CATEGORY_LABELS,
        beginDrag: context.interaction.beginDrag,
        updateDraggedItems: context.interaction.updateDraggedItems,
        placeDraggedPickerSprite: context.interaction.placeDraggedPickerSprite,
        clearPickerDrag: context.interaction.clearPickerDrag,
        persistDesignerUiState: context.mutations.persistDesignerUiState,
        getSelectionsInRect: context.selection.getSelectionsInRect,
        completeDrag: context.interaction.completeDrag,
        setDesignerActive: context.interaction.setDesignerActive,
        refreshModifierSnapInteraction: context.interaction.refreshModifierSnapInteraction,
        closeModal: context.modal.closeModal,
        openSavePreview: context.modal.openSavePreview,
        undo: context.history.undo,
        redo: context.history.redo,
        duplicateSelection: context.history.duplicateSelection,
        copySelection: context.history.copySelection,
        pasteSelection: context.history.pasteSelection,
        refreshPanel: context.panel.refreshPanel,
        restoreEditModeSnapshot: context.interaction.restoreEditModeSnapshot,
        deleteSelection: context.history.deleteSelection,
        rotateSelection: context.history.rotateSelection,
        nudgeSelection: context.history.nudgeSelection
    });
}

export function initializeInteractionCoordinatorFromMain(context: any) {
    return initializeInteractionCoordinator({
        state: context.core.state,
        host: context.core.host,
        refs: context.core.refs,
        spriteTypes: context.core.spriteTypes,
        historyLimit: context.core.historyLimit,
        paletteCount: context.core.paletteCount,
        clipboardEntriesRef: context.clipboardEntriesRef,
        getCategoryArray: context.data.getCategoryArray,
        teleporterApi: context.teleporters,
        getButtons: context.data.getButtons,
        runMutation: context.mutations.runMutation,
        normalizeRotation: context.utilities.normalizeRotation,
        normalizeSpriteTranslation: context.utilities.normalizeSpriteTranslation,
        categorySupportsTranslation: context.utilities.categorySupportsTranslation,
        refreshPanel: context.mutations.refreshPanel,
        persistDesignerUiState: context.mutations.persistDesignerUiState,
        setStatus: context.mutations.setStatus,
        selectionGeometry: context.selectionGeometry,
        serializeSelectionEntity: context.selection.serializeSelectionEntity,
        createPastedSelections: context.selection.createPastedSelections,
        getSnapshot: context.selection.getSnapshot,
        deepClone: context.utilities.deepClone,
        getCustomSpriteDefinitionById: context.customSprites.getCustomSpriteDefinitionById,
        invalidateOverviewBase: context.mutations.invalidateOverviewBase,
        updateDirtyState: context.mutations.updateDirtyState,
        syncEditModeSnapshot: context.mutations.syncEditModeSnapshot,
        getCurrentType: context.data.getCurrentType,
        geometry: context.geometry,
        screenToWorld: context.geometry.screenToWorld,
        designerSnapshotsEqual: context.selection.designerSnapshotsEqual,
        isTeleporterCompositeType: context.types.isTeleporterCompositeType,
        isButtonCompositeType: context.types.isButtonCompositeType,
        createButtonEntity: context.entityFactories.createButtonEntity,
        createCustomSpriteInstance: context.entityFactories.createCustomSpriteInstance,
        createDoorEntity: context.entityFactories.createDoorEntity,
        createCreatureEntity: context.entityFactories.createCreatureEntity,
        createCollectableEntity: context.entityFactories.createCollectableEntity,
        getDefaultCollectableWeight: context.defaults.getDefaultCollectableWeight,
        getDefaultCollectablePaletteCycle: context.defaults.getDefaultCollectablePaletteCycle,
        getPaletteCount: context.data.getPaletteCount,
        playMushroomPlacementSound: context.effects.playMushroomPlacementSound,
        clamp: context.utilities.clamp,
        renderSpritePreviewCanvas: context.rendering.renderSpritePreviewCanvas,
        updateSelectionFromInspectorState: context.selection.updateSelectionFromInspectorState,
        getCanvasPoint: context.geometry.getCanvasPoint,
        canGroupSelections: context.selection.canGroupSelections,
        groupSelectionsAsCustomSprite: context.selection.groupSelectionsAsCustomSprite,
        ungroupCustomSpriteSelection: context.selection.ungroupCustomSpriteSelection,
        deleteCustomSpriteSelectionDefinition: context.customSprites.deleteCustomSpriteSelectionDefinition,
        shouldMaskAstronaut: context.types.shouldMaskAstronaut,
        convertSelectionToCategory: context.selection.convertSelectionToCategory,
        canConvertCustomSpriteToButton: context.selection.canConvertCustomSpriteToButton
    });
}

export function initializeModalCoordinatorFromMain(context: any) {
    return initializeModalCoordinator({
        refs: context.core.refs,
        state: context.core.state,
        host: context.core.host,
        spriteTypes: context.core.spriteTypes,
        paletteCount: context.core.paletteCount,
        clearPngImportObjectUrl: context.pngImport.clearPngImportObjectUrl,
        getPaletteCount: context.data.getPaletteCount,
        getAuthoredWorldSnapshot: context.data.getAuthoredWorldSnapshot,
        getWorldSnapshotForValidationAndSave: context.data.getWorldSnapshotForValidationAndSave,
        stableStringify: context.utilities.stableStringify,
        snapshotsEqual: context.utilities.snapshotsEqual,
        paletteDefinitionsEqual: context.utilities.paletteDefinitionsEqual,
        deepClone: context.utilities.deepClone,
        serializeWorldData: context.utilities.serializeWorldData,
        syncPaletteCount: context.palette.syncPaletteCount,
        refreshSelectOptions: context.panel.refreshSelectOptions,
        refreshPaletteDesigner: context.palette.refreshPaletteDesigner,
        syncEditModeSnapshot: context.mutations.syncEditModeSnapshot,
        updateDirtyState: context.mutations.updateDirtyState,
        setStatus: context.mutations.setStatus,
        refreshPanel: context.mutations.refreshPanel,
        constants: context.constants,
        SPRITE_TRANSLATION_OPTIONS: context.types.SPRITE_TRANSLATION_OPTIONS,
        formatSpriteTranslation: context.utilities.formatSpriteTranslation,
        getDefaultImportWorldRect: context.pngImport.getDefaultImportWorldRect,
        getPngImportTypeNames: context.pngImport.getPngImportTypeNames,
        getPngImportTypeDefaults: context.pngImport.getPngImportTypeDefaults,
        setPngImportObjectUrl: context.pngImport.setPngImportObjectUrl,
        clamp: context.utilities.clamp,
        getPngChunkSelectionEntries: context.pngImport.getPngChunkSelectionEntries,
        getPngImportWorldSpanFromTileCount: context.pngImport.getPngImportWorldSpanFromTileCount,
        composePngChunkFolderSource: context.pngImport.composePngChunkFolderSource,
        pngImportDraftApi: context.pngImport.pngImportDraftApi,
        normalizeRotation: context.utilities.normalizeRotation,
        normalizeSpriteTranslation: context.utilities.normalizeSpriteTranslation,
        renderSpritePreviewCanvas: context.rendering.renderSpritePreviewCanvas,
        clearPreviewCanvas: context.rendering.clearPreviewCanvas,
        getPngImportSourceTileCount: context.pngImport.getPngImportSourceTileCount,
        getSuggestedPngImportWorldSpan: context.pngImport.getSuggestedPngImportWorldSpan,
        getDirectoryPicker: context.pngImport.getDirectoryPicker,
        readPngChunkFolderSelection: context.pngImport.readPngChunkFolderSelection,
        exportPngChunksToDirectory: context.pngImport.exportPngChunksToDirectory,
        toMapBlockData: context.utilities.toMapBlockData,
        applyPngImportDraft: context.pngImport.applyPngImportDraft
    });
}

export function initializeInspectorCoordinatorFromMain(context: any) {
    return initializeInspectorCoordinator({
        refs: context.core.refs,
        state: context.core.state,
        host: context.core.host,
        paletteCount: context.core.paletteCount,
        spriteTypes: context.core.spriteTypes,
        constants: context.constants,
        SPRITE_TRANSLATION_OPTIONS: context.types.SPRITE_TRANSLATION_OPTIONS,
        MOVEMENT_SETTINGS: context.types.MOVEMENT_SETTINGS,
        DESTRUCTION_SOURCE_OPTIONS: context.types.DESTRUCTION_SOURCE_OPTIONS,
        CREATURE_SOUND_MANIFEST: context.types.CREATURE_SOUND_MANIFEST,
        getSelectedItems: context.selection.getSelectedItems,
        getAstronautStartPosition: context.data.getAstronautStartPosition,
        getConvertTargetCategories: context.data.getConvertTargetCategories,
        getEffectiveButtonDefaultOverrides: context.defaults.getEffectiveButtonDefaultOverrides,
        runMutation: context.mutations.runMutation,
        clamp: context.utilities.clamp,
        setButtonDefaultOverridesFromButton: context.defaults.setButtonDefaultOverridesFromButton,
        resetButtonDefaultOverrides: context.defaults.resetButtonDefaultOverrides,
        getCustomSpriteDefinitionForInstance: context.customSprites.getCustomSpriteDefinitionForInstance,
        createCustomSpriteName: context.customSprites.createCustomSpriteName,
        renameCustomSpriteDefinition: context.customSprites.renameCustomSpriteDefinition,
        deleteCustomSpriteSelectionDefinition: context.customSprites.deleteCustomSpriteSelectionDefinition,
        applyEntityPositionWithTeleporterSync: context.teleporters.applyEntityPositionWithTeleporterSync,
        applyEntityRotationWithTeleporterSync: context.teleporters.applyEntityRotationWithTeleporterSync,
        normalizeRotation: context.utilities.normalizeRotation,
        categorySupportsTranslation: context.utilities.categorySupportsTranslation,
        normalizeSpriteTranslation: context.utilities.normalizeSpriteTranslation,
        getEffectivePaletteCycle: context.palette.getEffectivePaletteCycle,
        buildDefaultPaletteCycle: context.palette.buildDefaultPaletteCycle,
        parsePaletteCyclePalettes: context.parsers.parsePaletteCyclePalettes,
        shouldMaskAstronaut: context.types.shouldMaskAstronaut,
        findTeleporterForWorldBlock: context.teleporters.findTeleporterForWorldBlock,
        convertWorldTeleporterBlock: context.teleporters.convertWorldTeleporterBlock,
        renameTeleporterId: context.teleporters.renameTeleporterId,
        setStatus: context.mutations.setStatus,
        getDefaultDestructibleEnabled: context.defaults.getDefaultDestructibleEnabled,
        getDefaultDestructibleHealth: context.defaults.getDefaultDestructibleHealth,
        getDefaultDestructionSource: context.defaults.getDefaultDestructionSource,
        parseDoorIds: context.parsers.parseDoorIds,
        parseStringIds: context.parsers.parseStringIds,
        isTeleporterMode: context.types.isTeleporterMode,
        getButtonCapOffsetsRelativeToBox: context.defaults.getButtonCapOffsetsRelativeToBox,
        stableStringify: context.utilities.stableStringify,
        getDefaultCollectableWeight: context.defaults.getDefaultCollectableWeight,
        getDefaultCollectablePaletteCycle: context.defaults.getDefaultCollectablePaletteCycle,
        isGrenadeCollectableType: context.types.isGrenadeCollectableType,
        getDefaultGrenadeExplosionPower: context.defaults.getDefaultGrenadeExplosionPower,
        pendingInspectorFocusRef: context.pendingInspectorFocusRef
    });
}

export function initializeRuntimeAssemblyFromMain(context: any) {
    return initializeRuntimeAssembly({
        refs: context.core.refs,
        state: context.core.state,
        host: context.core.host,
        paletteCount: context.core.paletteCount,
        colorAliasNames: context.core.colorAliasNames,
        constants: context.constants,
        clamp: context.utilities.clamp,
        normalizeRotation: context.utilities.normalizeRotation,
        normalizeSpriteTranslation: context.utilities.normalizeSpriteTranslation,
        categorySupportsTranslation: context.utilities.categorySupportsTranslation,
        isTeleporterCompositeType: context.types.isTeleporterCompositeType,
        isButtonCompositeType: context.types.isButtonCompositeType,
        getSingleEditableSelection: context.selection.getSingleEditableSelection,
        getCustomSpriteDefinitionById: context.customSprites.getCustomSpriteDefinitionById,
        runMutation: context.mutations.runMutation,
        updateSelectionFromInspectorState: context.selection.updateSelectionFromInspectorState,
        setCurrentType: context.data.setCurrentType,
        renderSpritePickerGrid: context.rendering.renderSpritePickerGrid,
        persistDesignerUiState: context.mutations.persistDesignerUiState,
        applyEntityRotationWithTeleporterSync: context.teleporters.applyEntityRotationWithTeleporterSync,
        renderCurrentSpritePreview: context.rendering.renderCurrentSpritePreview,
        refreshModifierSnapInteraction: context.interaction.refreshModifierSnapInteraction,
        setSnapOffsets: context.interaction.setSnapOffsets,
        setSnapOffsetsFromPosition: context.interaction.setSnapOffsetsFromPosition,
        setStatus: context.mutations.setStatus,
        invalidateOverviewBase: context.mutations.invalidateOverviewBase,
        setDesignerActive: context.interaction.setDesignerActive,
        createNewPalette: context.palette.createNewPalette,
        cloneSelectedPalette: context.palette.cloneSelectedPalette,
        deleteSelectedPalette: context.palette.deleteSelectedPalette,
        savePaletteDesigner: context.palette.savePaletteDesigner,
        restoreEditModeSnapshot: context.interaction.restoreEditModeSnapshot,
        refreshPaletteDesigner: context.palette.refreshPaletteDesigner,
        openSavePreview: context.modal.openSavePreview,
        openPngImportModal: context.modal.openPngImportModal,
        openSpriteSheetNormalizationPreview: context.modal.openSpriteSheetNormalizationPreview,
        closeModal: context.modal.closeModal,
        modalCoordinator: context.modal.modalCoordinator,
        convertSelection: context.selection.convertSelection,
        focusOnCurrentWorldPosition: context.interaction.focusOnCurrentWorldPosition,
        moveLiveAstronautToViewCenter: context.interaction.moveLiveAstronautToViewCenter,
        setAstronautStartToViewCenter: context.interaction.setAstronautStartToViewCenter,
        getCanvasPoint: context.geometry.getCanvasPoint,
        screenToWorld: context.geometry.screenToWorld,
        getEntityAt: context.selection.getEntityAt,
        interactionHandlers: context.interaction.interactionHandlers,
        selectionApi: context.interaction.selectionApi,
        restoredViewportExpanded: context.interaction.restoredViewportExpanded,
        overviewBaseCanvas: context.core.overviewBaseCanvas,
        getMapBounds: context.data.getMapBounds,
        getChunkedWorldOverview: context.data.getChunkedWorldOverview,
        getCategoryArray: context.data.getCategoryArray,
        getEntityRect: context.geometry.getEntityRect,
        getAstronautStartPosition: context.data.getAstronautStartPosition,
        ensureOverviewWorldTilesLoaded: context.data.ensureOverviewWorldTilesLoaded,
        getOverviewWorldTiles: context.data.getOverviewWorldTiles,
        getSelectionVisuals: context.selection.getSelectionVisuals,
        drawCustomSpriteDefinitionAt: context.customSprites.drawCustomSpriteDefinitionAt,
        getCustomSpriteDefinitionForInstance: context.customSprites.getCustomSpriteDefinitionForInstance,
        normalizeRect: context.utilities.normalizeRect,
        dragGhostCanvas: context.rendering.dragGhostCanvas,
        dragGhostPadding: context.rendering.dragGhostPadding,
        dragGhostTargetSize: context.rendering.dragGhostTargetSize,
        renderCustomSpritePreviewCanvas: context.rendering.renderCustomSpritePreviewCanvas,
        renderButtonCompositePreviewCanvas: context.rendering.renderButtonCompositePreviewCanvas,
        createButtonEntity: context.entityFactories.createButtonEntity,
        getPlacementPreviewType: context.selection.getPlacementPreviewType,
        getTeleporterBaseRotationForPadRotation: context.teleporters.getTeleporterBaseRotationForPadRotation,
        drawMagnifier: context.rendering.drawMagnifier,
        resetSpriteResolversAndCache: context.lifecycle.resetSpriteResolversAndCache,
        styles: context.core.styles,
        resizeExpandedViewport: context.lifecycle.resizeExpandedViewport,
        applyDesignerOverlayZoomCompensation: context.lifecycle.applyDesignerOverlayZoomCompensation,
        setViewportExpanded: context.lifecycle.setViewportExpanded,
        refreshSelectOptions: context.panel.refreshSelectOptions,
        refreshPanel: context.panel.refreshPanel,
        setRenderLifecycle: context.lifecycle.setRenderLifecycle,
        getRenderLifecycle: context.lifecycle.getRenderLifecycle,
        pendingOverviewBaseInvalidationRef: context.pendingOverviewBaseInvalidationRef
    });
}
