import { bindWorldDesignerEventHandlers } from './world-designer-event-bindings.js';

export function bindWorldDesignerMainEventHandlers(deps: any) {
    const {
        core,
        palette,
        modal,
        selection,
        navigation,
        canvas
    } = deps;

    bindWorldDesignerEventHandlers({
        refs: core.refs,
        state: core.state,
        host: core.host,
        paletteCount: core.paletteCount,
        colorAliasNames: core.colorAliasNames,
        CATEGORY_LABELS: core.CATEGORY_LABELS,
        clamp: core.clamp,
        normalizeRotation: core.normalizeRotation,
        normalizeSpriteTranslation: core.normalizeSpriteTranslation,
        categorySupportsTranslation: core.categorySupportsTranslation,
        isTeleporterCompositeType: core.isTeleporterCompositeType,
        isButtonCompositeType: core.isButtonCompositeType,
        getSingleEditableSelection: core.getSingleEditableSelection,
        getCustomSpriteDefinitionById: core.getCustomSpriteDefinitionById,
        runMutation: core.runMutation,
        updateSelectionFromInspectorState: core.updateSelectionFromInspectorState,
        setCurrentType: core.setCurrentType,
        renderSpritePickerGrid: core.renderSpritePickerGrid,
        persistDesignerUiState: core.persistDesignerUiState,
        applyEntityRotationWithTeleporterSync: core.applyEntityRotationWithTeleporterSync,
        renderCurrentSpritePreview: core.renderCurrentSpritePreview,
        getSelectedItems: selection.getSelectedItems,
        refreshModifierSnapInteraction: core.refreshModifierSnapInteraction,
        setSnapOffsets: core.setSnapOffsets,
        setSnapOffsetsFromPosition: core.setSnapOffsetsFromPosition,
        refreshPanel: core.refreshPanel,
        setStatus: core.setStatus,
        setViewportExpanded: core.setViewportExpanded,
        createNewPalette: palette.createNewPalette,
        cloneSelectedPalette: palette.cloneSelectedPalette,
        deleteSelectedPalette: palette.deleteSelectedPalette,
        savePaletteDesigner: palette.savePaletteDesigner,
        restoreEditModeSnapshot: palette.restoreEditModeSnapshot,
        refreshPaletteDesigner: palette.refreshPaletteDesigner,
        invalidateOverviewBase: core.invalidateOverviewBase,
        openSavePreview: modal.openSavePreview,
        openPngImportModal: modal.openPngImportModal,
        deleteSelection: selection.deleteSelection,
        duplicateSelection: selection.duplicateSelection,
        reorderSelections: selection.reorderSelections,
        focusSelection: selection.focusSelection,
        convertSelection: selection.convertSelection,
        focusOnCurrentWorldPosition: navigation.focusOnCurrentWorldPosition,
        moveLiveAstronautToViewCenter: navigation.moveLiveAstronautToViewCenter,
        placeAtWorld: selection.placeAtWorld,
        setAstronautStartToViewCenter: navigation.setAstronautStartToViewCenter,
        openSpriteSheetNormalizationPreview: modal.openSpriteSheetNormalizationPreview,
        closeModal: modal.closeModal,
        modalConfirmActionRef: {
            get: modal.getModalConfirmAction
        },
        closeContextMenu: selection.closeContextMenu,
        handleOverviewMouseDown: canvas.handleOverviewMouseDown,
        handleOverviewMouseMove: canvas.handleOverviewMouseMove,
        handleOverviewMouseUp: canvas.handleOverviewMouseUp,
        getCanvasPoint: canvas.getCanvasPoint,
        screenToWorld: canvas.screenToWorld,
        getEntityAt: canvas.getEntityAt,
        openContextMenu: selection.openContextMenu,
        openEmptyContextMenu: selection.openEmptyContextMenu,
        handleCanvasMouseDown: canvas.handleCanvasMouseDown,
        handleCanvasMouseMove: canvas.handleCanvasMouseMove,
        handleCanvasMouseLeave: canvas.handleCanvasMouseLeave,
        handleCanvasMouseUp: canvas.handleCanvasMouseUp,
        handleKeyDown: canvas.handleKeyDown,
        handleKeyUp: canvas.handleKeyUp,
        handleWindowMouseDown: canvas.handleWindowMouseDown,
        handleWindowBeforeUnload: canvas.handleWindowBeforeUnload,
        resizeExpandedViewport: canvas.resizeExpandedViewport,
        applyDesignerOverlayZoomCompensation: canvas.applyDesignerOverlayZoomCompensation,
        setDesignerActive: core.setDesignerActive
    });
}
